/**
 * MULTI-PAGE WEBSITE PREVIEW COMPONENT
 *
 * Compact preview card + fullscreen preview mode.
 * Fullscreen view extracted to MultiPagePreviewFullscreen.
 */

'use client';

import { useState, useCallback, useEffect } from 'react';
import type { MultiPageWebsite, WebsitePage } from '@/app/chat/types';
import { MultiPagePreviewFullscreen } from './MultiPagePreviewFullscreen';

interface MultiPagePreviewProps {
  website: MultiPageWebsite;
  onCodeChange?: (pages: WebsitePage[]) => void;
  onDeploy?: () => void;
  onPushToGitHub?: () => void;
}

export default function MultiPagePreview({
  website,
  onCodeChange,
  onDeploy,
  onPushToGitHub,
}: MultiPagePreviewProps) {
  const [pages] = useState<WebsitePage[]>(website.pages);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  // Handle messages from iframe (for edit mode in fullscreen)
  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.data.type === 'FORGE_ELEMENT_CLICK') {
        // Handled by fullscreen component
      }
    };
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, []);

  const handleCopyAll = useCallback(async () => {
    const allCode = pages.map((p: WebsitePage) => `<!-- ${p.name} (${p.slug}.html) -->\n${p.code}`).join('\n\n' + '='.repeat(80) + '\n\n');
    try {
      await navigator.clipboard.writeText(allCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  }, [pages]);

  const handleDownloadZip = useCallback(async () => {
    setDownloading(true);
    try {
      const JSZip = (await import('jszip')).default;
      const zip = new JSZip();

      pages.forEach((page: WebsitePage) => {
        zip.file(`${page.slug}.html`, page.code);
      });

      if (website.sharedStyles) zip.file('styles.css', website.sharedStyles);
      if (website.sharedScripts) zip.file('scripts.js', website.sharedScripts);

      zip.file('package.json', JSON.stringify({
        name: website.businessName?.toLowerCase().replace(/\s+/g, '-') || 'my-website',
        version: '1.0.0',
        description: website.description || 'Generated by FORGE AI',
        scripts: { start: 'npx serve .' },
      }, null, 2));

      zip.file('README.md', `# ${website.title}\n\n${website.description || ''}\n\nGenerated by FORGE AI Website Builder.\n\n## Pages\n${pages.map((p: WebsitePage) => `- ${p.name} (${p.slug}.html)`).join('\n')}\n`);

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${website.businessName?.toLowerCase().replace(/\s+/g, '-') || 'website'}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Failed to create ZIP:', err);
    }
    setDownloading(false);
  }, [pages, website]);

  return (
    <>
      {/* Compact preview card */}
      <div className="mb-3 rounded-xl border border-white/10 bg-white/5 overflow-hidden max-w-xl">
        <div className="flex items-center justify-between px-4 py-3 bg-gradient-to-r from-violet-500/10 to-cyan-500/10 border-b border-white/10">
          <div className="flex items-center gap-2">
            <span className="text-xl">🌐</span>
            <div>
              <div className="font-medium text-white text-sm">{website.title}</div>
              <div className="text-xs text-gray-400">{pages.length} pages</div>
            </div>
          </div>
          <div className="flex items-center gap-1">
            {pages.map((page: WebsitePage, i: number) => (
              <span key={i} className="text-xs px-2 py-0.5 rounded bg-white/10 text-gray-300">
                {page.icon || '📄'} {page.name}
              </span>
            ))}
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2 px-4 py-3">
          <button
            onClick={() => setIsFullscreen(true)}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-gradient-to-r from-violet-500 to-cyan-500 text-white text-sm font-medium hover:from-violet-600 hover:to-cyan-600 transition-all shadow-lg shadow-violet-500/25"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
            </svg>
            Open Preview
          </button>

          <button onClick={handleDownloadZip} disabled={downloading} className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white/10 text-white text-sm font-medium hover:bg-white/20 transition-all disabled:opacity-50">
            {downloading ? (
              <svg className="w-4 h-4 animate-spin" viewBox="0 0 24 24" aria-hidden="true">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
            ) : (
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
            )}
            Download ZIP
          </button>

          <button onClick={handleCopyAll} className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white/10 text-white text-sm font-medium hover:bg-white/20 transition-all">
            {copied ? (<><span aria-hidden="true">✅</span> Copied!</>) : (<><span aria-hidden="true">📋</span> Copy All</>)}
          </button>

          {onPushToGitHub && (
            <button onClick={onPushToGitHub} className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white/10 text-white text-sm font-medium hover:bg-white/20 transition-all">
              <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
              </svg>
              Push to GitHub
            </button>
          )}

          {onDeploy && (
            <button onClick={onDeploy} className="flex items-center gap-2 px-4 py-2 rounded-lg bg-gradient-to-r from-black to-gray-800 text-white text-sm font-medium hover:from-gray-800 hover:to-gray-700 transition-all border border-white/20">
              <span aria-hidden="true">▲</span>
              Deploy to Vercel
            </button>
          )}
        </div>
      </div>

      {isFullscreen && (
        <MultiPagePreviewFullscreen
          website={website}
          pages={pages}
          onClose={() => setIsFullscreen(false)}
          onCodeChange={onCodeChange}
          onDeploy={onDeploy}
          onPushToGitHub={onPushToGitHub}
          onDownloadZip={handleDownloadZip}
        />
      )}
    </>
  );
}
