/**
 * DATABASE DESIGNER DEMO COMPONENT
 *
 * PURPOSE:
 * - Landing page showcase for Database Designer
 * - Visual schema representation
 * - Supabase integration demo
 */

'use client';

import { useState, useEffect } from 'react';

interface Column {
  name: string;
  type: string;
  pk?: boolean;
  unique?: boolean;
  fk?: string;
}

interface Table {
  name: string;
  icon: string;
  columns: Column[];
}

const TABLES: Table[] = [
  {
    name: 'users',
    icon: '👤',
    columns: [
      { name: 'id', type: 'uuid', pk: true },
      { name: 'email', type: 'text', unique: true },
      { name: 'name', type: 'text' },
      { name: 'created_at', type: 'timestamp' },
    ],
  },
  {
    name: 'posts',
    icon: '📝',
    columns: [
      { name: 'id', type: 'uuid', pk: true },
      { name: 'user_id', type: 'uuid', fk: 'users.id' },
      { name: 'title', type: 'text' },
      { name: 'content', type: 'text' },
      { name: 'published', type: 'boolean' },
    ],
  },
  {
    name: 'comments',
    icon: '💬',
    columns: [
      { name: 'id', type: 'uuid', pk: true },
      { name: 'post_id', type: 'uuid', fk: 'posts.id' },
      { name: 'user_id', type: 'uuid', fk: 'users.id' },
      { name: 'content', type: 'text' },
    ],
  },
];

const SQL_OUTPUT = `-- Generated by JCIL.AI Database Designer

CREATE TABLE "users" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "email" TEXT NOT NULL UNIQUE,
  "name" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE "posts" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "user_id" UUID NOT NULL,
  "title" TEXT NOT NULL,
  "content" TEXT,
  "published" BOOLEAN DEFAULT false,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);

ALTER TABLE "posts" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "users_own_posts" ON "posts"
  FOR ALL USING (auth.uid() = user_id);`;

export default function DatabaseDemo() {
  const [visibleTables, setVisibleTables] = useState(0);
  const [showSQL, setShowSQL] = useState(false);
  const [sqlTyped, setSqlTyped] = useState('');

  // Animate table appearance
  useEffect(() => {
    const timer = setInterval(() => {
      setVisibleTables((prev) => {
        if (prev >= TABLES.length) {
          clearInterval(timer);
          setTimeout(() => setShowSQL(true), 500);
          return prev;
        }
        return prev + 1;
      });
    }, 600);

    return () => clearInterval(timer);
  }, []);

  // Type SQL output
  useEffect(() => {
    if (!showSQL) return;

    let index = 0;
    const typeInterval = setInterval(() => {
      if (index <= SQL_OUTPUT.length) {
        setSqlTyped(SQL_OUTPUT.slice(0, index));
        index += 5;
      } else {
        clearInterval(typeInterval);
        // Reset after pause
        setTimeout(() => {
          setVisibleTables(0);
          setShowSQL(false);
          setSqlTyped('');
        }, 4000);
      }
    }, 20);

    return () => clearInterval(typeInterval);
  }, [showSQL]);

  return (
    <div className="w-full max-w-5xl mx-auto">
      {/* Header */}
      <div className="text-center mb-8">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-500/10 border border-emerald-500/30 mb-4">
          <span className="text-emerald-400">🗄️</span>
          <span className="text-sm font-medium text-emerald-300">Database Designer</span>
        </div>
        <h3 className="text-2xl sm:text-3xl font-bold text-white mb-3">
          Schema to Supabase in Seconds
        </h3>
        <p className="text-slate-400 max-w-2xl mx-auto">
          Describe your data model and watch. The AI designs your schema, generates SQL with
          Row Level Security, and deploys directly to Supabase.
        </p>
      </div>

      {/* Demo Window */}
      <div className="rounded-2xl overflow-hidden shadow-2xl shadow-emerald-500/10 border border-slate-700/50">
        {/* Window Chrome */}
        <div className="bg-slate-800 px-4 py-2 flex items-center justify-between border-b border-slate-700/50">
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1.5">
              <div className="w-3 h-3 rounded-full bg-red-500" />
              <div className="w-3 h-3 rounded-full bg-yellow-500" />
              <div className="w-3 h-3 rounded-full bg-green-500" />
            </div>
            <span className="text-sm font-medium text-white">Database Designer</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-2 px-3 py-1 rounded-lg bg-emerald-500/10 border border-emerald-500/30">
              <svg className="w-4 h-4 text-emerald-400" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/>
              </svg>
              <span className="text-xs text-emerald-400">Supabase Connected</span>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="bg-slate-900 p-6">
          {/* Split View */}
          <div className="grid grid-cols-2 gap-6">
            {/* Visual Schema */}
            <div className="space-y-4">
              <h4 className="text-sm font-medium text-slate-300 mb-3">Visual Schema</h4>

              {TABLES.slice(0, visibleTables).map((table, tableIndex) => (
                <div
                  key={table.name}
                  className="bg-slate-800/50 rounded-xl border border-slate-700/50 overflow-hidden transform transition-all duration-500"
                  style={{
                    animation: 'slideIn 0.5s ease-out',
                  }}
                >
                  {/* Table Header */}
                  <div className="flex items-center gap-2 px-4 py-2 bg-emerald-500/10 border-b border-slate-700/50">
                    <span>{table.icon}</span>
                    <span className="font-medium text-emerald-400">{table.name}</span>
                  </div>

                  {/* Columns */}
                  <div className="p-2 space-y-1">
                    {table.columns.map((col) => (
                      <div
                        key={col.name}
                        className="flex items-center justify-between px-2 py-1 rounded bg-slate-700/30 text-sm"
                      >
                        <div className="flex items-center gap-2">
                          {col.pk && <span className="text-yellow-400 text-xs">🔑</span>}
                          {col.fk && <span className="text-blue-400 text-xs">🔗</span>}
                          <span className="text-slate-300">{col.name}</span>
                        </div>
                        <span className="text-xs text-slate-500">{col.type}</span>
                      </div>
                    ))}
                  </div>

                  {/* Relationship Lines (simplified) */}
                  {tableIndex > 0 && (
                    <div className="px-4 py-2 border-t border-slate-700/50 text-xs text-slate-500">
                      → {table.columns.find((c) => c.fk)?.fk}
                    </div>
                  )}
                </div>
              ))}

              {visibleTables < TABLES.length && (
                <div className="flex items-center justify-center py-4">
                  <span className="w-6 h-6 border-2 border-emerald-400 border-t-transparent rounded-full animate-spin" />
                </div>
              )}
            </div>

            {/* SQL Output */}
            <div>
              <h4 className="text-sm font-medium text-slate-300 mb-3">Generated SQL</h4>
              <div className="bg-slate-800/50 rounded-xl border border-slate-700/50 p-4 h-[300px] overflow-y-auto">
                <pre className="font-mono text-xs text-slate-300 whitespace-pre-wrap">
                  {sqlTyped}
                  {showSQL && sqlTyped.length < SQL_OUTPUT.length && (
                    <span className="inline-block w-2 h-3 bg-emerald-400 animate-pulse" />
                  )}
                </pre>
              </div>
            </div>
          </div>

          {/* Deploy Button */}
          {sqlTyped.length >= SQL_OUTPUT.length && (
            <div className="mt-6 text-center">
              <button className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-emerald-600 text-white font-semibold hover:bg-emerald-500 transition">
                <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/>
                </svg>
                Deploy to Supabase
              </button>
            </div>
          )}
        </div>

        {/* Status Bar */}
        <div className="flex items-center justify-between px-4 py-1.5 bg-slate-800 border-t border-slate-700/50 text-xs text-slate-500">
          <div className="flex items-center gap-4">
            <span>{visibleTables} tables</span>
            <span>RLS enabled</span>
          </div>
          <div className="flex items-center gap-4">
            <span>PostgreSQL</span>
            <span>Supabase</span>
          </div>
        </div>
      </div>

      {/* Feature Highlights */}
      <div className="mt-8 grid grid-cols-3 gap-4">
        <div className="text-center p-4">
          <div className="text-2xl mb-2">🎨</div>
          <div className="text-white font-medium text-sm">Visual Designer</div>
          <div className="text-slate-500 text-xs">See your schema</div>
        </div>
        <div className="text-center p-4">
          <div className="text-2xl mb-2">🔒</div>
          <div className="text-white font-medium text-sm">RLS Policies</div>
          <div className="text-slate-500 text-xs">Auto-generated security</div>
        </div>
        <div className="text-center p-4">
          <div className="text-2xl mb-2">⚡</div>
          <div className="text-white font-medium text-sm">One-Click Deploy</div>
          <div className="text-slate-500 text-xs">Straight to Supabase</div>
        </div>
      </div>
    </div>
  );
}
