/**
 * TECH DEMO COMPONENT
 *
 * PURPOSE:
 * - Show real developer-focused capabilities
 * - Project scaffolding visualization
 * - Architecture generation demo
 * - Appeal to serious developers
 */

'use client';

import { useState, useEffect } from 'react';

// Simulated project scaffolding output
const PROJECT_STRUCTURE = [
  { path: 'src/', type: 'folder', indent: 0 },
  { path: 'src/app/', type: 'folder', indent: 1 },
  { path: 'src/app/page.tsx', type: 'file', indent: 2, lang: 'tsx' },
  { path: 'src/app/layout.tsx', type: 'file', indent: 2, lang: 'tsx' },
  { path: 'src/app/api/', type: 'folder', indent: 2 },
  { path: 'src/app/api/chat/route.ts', type: 'file', indent: 3, lang: 'ts' },
  { path: 'src/app/api/auth/route.ts', type: 'file', indent: 3, lang: 'ts' },
  { path: 'src/components/', type: 'folder', indent: 1 },
  { path: 'src/components/Chat.tsx', type: 'file', indent: 2, lang: 'tsx' },
  { path: 'src/components/Sidebar.tsx', type: 'file', indent: 2, lang: 'tsx' },
  { path: 'src/components/Header.tsx', type: 'file', indent: 2, lang: 'tsx' },
  { path: 'src/lib/', type: 'folder', indent: 1 },
  { path: 'src/lib/ai/', type: 'folder', indent: 2 },
  { path: 'src/lib/ai/agent.ts', type: 'file', indent: 3, lang: 'ts' },
  { path: 'src/lib/ai/tools.ts', type: 'file', indent: 3, lang: 'ts' },
  { path: 'src/lib/db/', type: 'folder', indent: 2 },
  { path: 'src/lib/db/client.ts', type: 'file', indent: 3, lang: 'ts' },
  { path: 'package.json', type: 'file', indent: 0, lang: 'json' },
  { path: 'tsconfig.json', type: 'file', indent: 0, lang: 'json' },
  { path: '.env.example', type: 'file', indent: 0, lang: 'env' },
];

const CODE_SAMPLE = `// src/lib/ai/agent.ts - Auto-generated by JCIL.AI

import { z } from 'zod';
import { Tool, ToolRegistry } from './tools';

export interface AgentConfig {
  model: string;
  maxRetries: number;
  autonomousMode: boolean;
}

export class Agent {
  private tools: ToolRegistry;
  private memory: Map<string, unknown>;

  constructor(config: AgentConfig) {
    this.tools = new ToolRegistry();
    this.memory = new Map();
    this.registerDefaultTools();
  }

  async execute(task: string): Promise<Result> {
    // 1. Classify the task
    const taskType = await this.classify(task);

    // 2. Select appropriate tool
    const tool = this.tools.get(taskType);

    // 3. Execute with auto-retry
    let result = await tool.execute(task);
    let retries = 0;

    while (!result.success && retries < 3) {
      const fix = await this.analyzeFix(result.error);
      result = await tool.execute(fix.correctedTask);
      retries++;
    }

    // 4. Store in memory for context
    this.memory.set(task, result);

    return result;
  }
}`;

const TERMINAL_OUTPUT = [
  { type: 'command', text: '$ jcil scaffold ai-chat-app --framework next --db supabase' },
  { type: 'info', text: '🔍 Analyzing project requirements...' },
  { type: 'info', text: '📋 Planning file structure (18 files)...' },
  { type: 'success', text: '✓ Created src/app/page.tsx' },
  { type: 'success', text: '✓ Created src/app/layout.tsx' },
  { type: 'success', text: '✓ Created src/app/api/chat/route.ts' },
  { type: 'success', text: '✓ Created src/components/Chat.tsx' },
  { type: 'success', text: '✓ Created src/lib/ai/agent.ts' },
  { type: 'success', text: '✓ Created src/lib/ai/tools.ts' },
  { type: 'info', text: '📦 Installing dependencies...' },
  { type: 'success', text: '✓ Installed 24 packages' },
  { type: 'info', text: '🚀 Pushing to GitHub...' },
  { type: 'success', text: '✓ Created repository: github.com/user/ai-chat-app' },
  { type: 'success', text: '✓ Pushed 18 files to main branch' },
  { type: 'done', text: '' },
  { type: 'complete', text: '🎉 Project ready! Run: cd ai-chat-app && npm run dev' },
];

export default function TechDemo() {
  const [visibleFiles, setVisibleFiles] = useState(0);
  const [visibleTerminal, setVisibleTerminal] = useState(0);
  const [activeTab, setActiveTab] = useState<'structure' | 'code' | 'terminal'>('terminal');
  const [codeVisible, setCodeVisible] = useState(0);

  // Animate file structure
  useEffect(() => {
    if (activeTab !== 'structure') return;
    const timer = setInterval(() => {
      setVisibleFiles((prev) => {
        if (prev >= PROJECT_STRUCTURE.length) {
          clearInterval(timer);
          return prev;
        }
        return prev + 1;
      });
    }, 80);
    return () => clearInterval(timer);
  }, [activeTab]);

  // Animate terminal
  useEffect(() => {
    if (activeTab !== 'terminal') return;
    const timer = setInterval(() => {
      setVisibleTerminal((prev) => {
        if (prev >= TERMINAL_OUTPUT.length) {
          clearInterval(timer);
          return prev;
        }
        return prev + 1;
      });
    }, 200);
    return () => clearInterval(timer);
  }, [activeTab]);

  // Animate code
  useEffect(() => {
    if (activeTab !== 'code') return;
    const timer = setInterval(() => {
      setCodeVisible((prev) => {
        if (prev >= CODE_SAMPLE.length) {
          clearInterval(timer);
          return prev;
        }
        return prev + 8; // 8 chars at a time
      });
    }, 15);
    return () => clearInterval(timer);
  }, [activeTab]);

  const getFileIcon = (type: string, lang?: string) => {
    if (type === 'folder') return '📁';
    switch (lang) {
      case 'tsx':
      case 'ts':
        return '🔷';
      case 'json':
        return '📋';
      case 'env':
        return '🔐';
      default:
        return '📄';
    }
  };

  const getTerminalColor = (type: string) => {
    switch (type) {
      case 'command':
        return 'text-cyan-400';
      case 'info':
        return 'text-blue-400';
      case 'success':
        return 'text-green-400';
      case 'complete':
        return 'text-yellow-400 font-bold';
      default:
        return 'text-slate-400';
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto">
      {/* Header */}
      <div className="text-center mb-8">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-green-500/10 border border-green-500/30 mb-4">
          <span className="text-green-400">💻</span>
          <span className="text-sm font-medium text-green-300">Built for Developers</span>
        </div>
        <h3 className="text-2xl sm:text-3xl font-bold text-white mb-3">
          Full Project Scaffolding in Seconds
        </h3>
        <p className="text-slate-400 max-w-2xl mx-auto">
          Say &quot;build me an AI chat app with Next.js and Supabase&quot; and watch.
          The agent plans, generates, and deploys your entire project to GitHub.
        </p>
      </div>

      {/* Demo Window */}
      <div className="rounded-2xl overflow-hidden shadow-2xl shadow-purple-500/10 border border-slate-700/50">
        {/* Tab Bar */}
        <div className="bg-slate-800 px-4 py-2 flex items-center gap-4 border-b border-slate-700/50">
          <div className="flex items-center gap-1.5 mr-4">
            <div className="w-3 h-3 rounded-full bg-red-500" />
            <div className="w-3 h-3 rounded-full bg-yellow-500" />
            <div className="w-3 h-3 rounded-full bg-green-500" />
          </div>
          <button
            onClick={() => {
              setActiveTab('terminal');
              setVisibleTerminal(0);
            }}
            className={`px-3 py-1 rounded-md text-sm font-medium transition ${
              activeTab === 'terminal'
                ? 'bg-slate-700 text-white'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Terminal
          </button>
          <button
            onClick={() => {
              setActiveTab('structure');
              setVisibleFiles(0);
            }}
            className={`px-3 py-1 rounded-md text-sm font-medium transition ${
              activeTab === 'structure'
                ? 'bg-slate-700 text-white'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            File Structure
          </button>
          <button
            onClick={() => {
              setActiveTab('code');
              setCodeVisible(0);
            }}
            className={`px-3 py-1 rounded-md text-sm font-medium transition ${
              activeTab === 'code'
                ? 'bg-slate-700 text-white'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Generated Code
          </button>
          <div className="ml-auto">
            <span className="text-xs text-slate-500">JCIL.AI Agent</span>
          </div>
        </div>

        {/* Content Area */}
        <div className="bg-slate-900 min-h-[400px] max-h-[500px] overflow-y-auto">
          {/* Terminal View */}
          {activeTab === 'terminal' && (
            <div className="p-4 font-mono text-sm">
              {TERMINAL_OUTPUT.slice(0, visibleTerminal).map((line, i) => (
                <div key={i} className={`${getTerminalColor(line.type)} mb-1`}>
                  {line.text}
                </div>
              ))}
              {visibleTerminal < TERMINAL_OUTPUT.length && (
                <span className="inline-block w-2 h-4 bg-green-400 animate-pulse" />
              )}
            </div>
          )}

          {/* File Structure View */}
          {activeTab === 'structure' && (
            <div className="p-4 font-mono text-sm">
              {PROJECT_STRUCTURE.slice(0, visibleFiles).map((item, i) => (
                <div
                  key={i}
                  className="flex items-center gap-2 text-slate-300 mb-0.5"
                  style={{ paddingLeft: `${item.indent * 16}px` }}
                >
                  <span className="text-xs">{getFileIcon(item.type, item.lang)}</span>
                  <span className={item.type === 'folder' ? 'text-blue-400' : 'text-slate-300'}>
                    {item.path.split('/').pop()}
                  </span>
                </div>
              ))}
              {visibleFiles < PROJECT_STRUCTURE.length && (
                <span className="inline-block w-2 h-4 bg-blue-400 animate-pulse ml-4" />
              )}
              {visibleFiles >= PROJECT_STRUCTURE.length && (
                <div className="mt-4 pt-4 border-t border-slate-700/50 text-green-400">
                  ✓ 18 files generated in 2.3s
                </div>
              )}
            </div>
          )}

          {/* Code View */}
          {activeTab === 'code' && (
            <div className="p-4">
              <div className="flex items-center gap-2 text-slate-500 text-xs mb-3">
                <span>src/lib/ai/agent.ts</span>
                <span className="px-2 py-0.5 rounded bg-blue-500/20 text-blue-400">TypeScript</span>
              </div>
              <pre className="font-mono text-sm text-slate-300 leading-relaxed overflow-x-auto">
                <code>
                  {CODE_SAMPLE.slice(0, codeVisible)}
                  {codeVisible < CODE_SAMPLE.length && (
                    <span className="inline-block w-2 h-4 bg-purple-400 animate-pulse" />
                  )}
                </code>
              </pre>
            </div>
          )}
        </div>

        {/* Status Bar */}
        <div className="bg-slate-800 px-4 py-2 border-t border-slate-700/50 flex items-center justify-between text-xs">
          <div className="flex items-center gap-4 text-slate-500">
            <span className="flex items-center gap-1">
              <span className="w-2 h-2 rounded-full bg-green-400" />
              Agent Active
            </span>
            <span>Autonomous Mode</span>
          </div>
          <div className="flex items-center gap-4 text-slate-500">
            <span>TypeScript</span>
            <span>Next.js 14</span>
            <span>UTF-8</span>
          </div>
        </div>
      </div>

      {/* Feature Highlights */}
      <div className="mt-8 grid grid-cols-3 gap-4">
        <div className="text-center p-4">
          <div className="text-2xl mb-2">⚡</div>
          <div className="text-white font-medium text-sm">Instant Generation</div>
          <div className="text-slate-500 text-xs">18 files in seconds</div>
        </div>
        <div className="text-center p-4">
          <div className="text-2xl mb-2">🔄</div>
          <div className="text-white font-medium text-sm">Self-Correcting</div>
          <div className="text-slate-500 text-xs">Auto-fix on errors</div>
        </div>
        <div className="text-center p-4">
          <div className="text-2xl mb-2">📦</div>
          <div className="text-white font-medium text-sm">GitHub Deploy</div>
          <div className="text-slate-500 text-xs">Auto-push to repo</div>
        </div>
      </div>
    </div>
  );
}
