/**
 * CHAT TYPES
 *
 * PURPOSE:
 * - Shared type definitions for chat components
 * - Ensures type consistency across the chat interface
 */

export interface Chat {
  id: string;
  title: string;
  summary?: string;
  folder?: string;
  isPinned: boolean;
  lastMessage: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Citation {
  title: string;
  url: string;
  snippet?: string;
}

export interface VideoJob {
  job_id: string;
  status: 'queued' | 'in_progress' | 'completed' | 'failed';
  progress: number;
  model: string;
  size: string;
  seconds: number;
  status_url: string;
  download_url: string;
  error?: {
    code: string;
    message: string;
  };
}

export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  toolCalls?: ToolCall[];
  attachments?: Attachment[];
  imageUrl?: string; // For AI-generated images
  videoUrl?: string; // For completed video generations
  videoJob?: VideoJob; // For video generation in progress
  products?: ShopProduct[]; // For Amazon shopping results
  citations?: Citation[]; // Source citations from Live Search (with title and URL)
  sourcesUsed?: number; // Number of sources used in search
  model?: string; // Model used for this response (gpt-5-nano, gpt-5-mini, etc.)
  searchProvider?: string; // Search provider used (perplexity, etc.) - for admin display
  files?: GeneratedFile[]; // Files generated by Anthropic Skills (xlsx, pptx, docx, pdf)
  timestamp: Date;
  isStreaming?: boolean;
}

export interface GeneratedFile {
  file_id: string;
  filename: string;
  mime_type: string;
  download_url: string;
}

export interface ToolCall {
  id: string;
  name: string;
  status: 'pending' | 'running' | 'completed' | 'error';
}

export interface Attachment {
  id: string;
  name: string;
  type: string;
  size: number;
  url?: string;
  thumbnail?: string;
}

export interface ShopProduct {
  title: string;
  price: string;
  rating?: string;
  image?: string;
  url: string;
}
