/**
 * CONNECTORS CONFIGURATION
 * Defines all available external service integrations
 */

export interface ConnectorField {
  key: string;
  label: string;
  placeholder: string;
  type?: 'text' | 'password';
  helpText?: string;
}

export interface ConnectorConfig {
  id: string;
  name: string;
  description: string;
  category: 'code' | 'ecommerce' | 'docs' | 'project' | 'analytics' | 'ai' | 'communication' | 'website' | 'finance';
  icon: string; // We'll use simple text icons or could be URLs
  color: string; // Brand color for UI
  tokenLabel: string; // e.g., "Personal Access Token" or "API Key"
  tokenHelpUrl: string; // Link to docs on how to get the token
  placeholder: string; // Placeholder text for input
  capabilities: string[]; // What the AI can do with this connector
  comingSoon?: boolean; // If true, show as "Coming Soon"
  fields?: ConnectorField[]; // For connectors that need multiple inputs (e.g., Supabase)
  fieldSeparator?: string; // How to join multiple fields when storing (default: '|')
}

export const CONNECTORS: ConnectorConfig[] = [
  // CODE & DEV
  {
    id: 'github',
    name: 'GitHub',
    description: 'Read, write, and manage code repositories',
    category: 'code',
    icon: '🐙',
    color: '#24292e',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://github.com/settings/tokens',
    placeholder: 'ghp_xxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Read repository files',
      'Create and edit files',
      'Create commits and branches',
      'Open pull requests',
      'Manage issues',
    ],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'Manage GitLab repositories and CI/CD',
    category: 'code',
    icon: '🦊',
    color: '#fc6d26',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://gitlab.com/-/profile/personal_access_tokens',
    placeholder: 'glpat-xxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Read repository files',
      'List and manage projects',
      'View merge requests and issues',
      'Monitor CI/CD pipelines',
    ],
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Manage deployments and projects',
    category: 'code',
    icon: '▲',
    color: '#000000',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://vercel.com/account/tokens',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List projects',
      'View deployments',
      'Check deployment status',
      'View environment variables',
      'Trigger redeployments',
    ],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Manage database and authentication',
    category: 'code',
    icon: '⚡',
    color: '#3ecf8e',
    tokenLabel: 'Project Credentials',
    tokenHelpUrl: 'https://supabase.com/dashboard/project/_/settings/api',
    placeholder: '', // Not used when fields is defined
    capabilities: [
      'List and query database tables',
      'Insert, update, delete records',
      'View table schemas',
      'List authenticated users',
      'Run custom queries',
    ],
    fields: [
      {
        key: 'url',
        label: 'Project URL',
        placeholder: 'https://abcd1234.supabase.co',
        type: 'text',
        helpText: 'Find this in Settings → API → Project URL',
      },
      {
        key: 'key',
        label: 'Service Role Key',
        placeholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        type: 'password',
        helpText: 'Find this in Settings → API → service_role (secret)',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'Manage DNS, Workers, and CDN',
    category: 'code',
    icon: '☁️',
    color: '#f38020',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List and manage DNS zones',
      'Create, update, delete DNS records',
      'Purge cache',
      'List and manage Workers',
      'View analytics',
    ],
  },
  {
    id: 'upstash',
    name: 'Upstash',
    description: 'Serverless Redis database',
    category: 'code',
    icon: '🔺',
    color: '#00e9a3',
    tokenLabel: 'Redis Credentials',
    tokenHelpUrl: 'https://console.upstash.com/',
    placeholder: '',
    capabilities: [
      'Get, set, delete keys',
      'Hash operations',
      'List operations',
      'Key management',
      'Database info',
    ],
    fields: [
      {
        key: 'url',
        label: 'REST URL',
        placeholder: 'https://xxxxxx.upstash.io',
        type: 'text',
        helpText: 'Found in your Upstash Redis database details',
      },
      {
        key: 'token',
        label: 'REST Token',
        placeholder: 'AxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxQ=',
        type: 'password',
        helpText: 'Found in your Upstash Redis database details',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'n8n',
    name: 'n8n',
    description: 'Workflow automation platform',
    category: 'code',
    icon: '🔗',
    color: '#ea4b71',
    tokenLabel: 'n8n Credentials',
    tokenHelpUrl: 'https://docs.n8n.io/api/',
    placeholder: '',
    capabilities: [
      'List and manage workflows',
      'Execute workflows',
      'View executions',
      'Trigger webhooks',
      'Activate/deactivate workflows',
    ],
    fields: [
      {
        key: 'url',
        label: 'n8n Host URL',
        placeholder: 'https://your-n8n.example.com',
        type: 'text',
        helpText: 'Your n8n instance URL (self-hosted or cloud)',
      },
      {
        key: 'token',
        label: 'API Key',
        placeholder: 'n8n_api_xxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Create in n8n Settings → API',
      },
    ],
    fieldSeparator: '|',
  },

  // E-COMMERCE
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Manage your Shopify store',
    category: 'ecommerce',
    icon: '🛒',
    color: '#96bf48',
    tokenLabel: 'Store Credentials',
    tokenHelpUrl: 'https://admin.shopify.com/store/YOUR_STORE/settings/apps/development',
    placeholder: '',
    capabilities: [
      'View and edit products',
      'Manage inventory',
      'View orders and customers',
      'Update prices',
      'List collections',
    ],
    fields: [
      {
        key: 'store',
        label: 'Store Domain',
        placeholder: 'your-store.myshopify.com',
        type: 'text',
        helpText: 'Your Shopify store domain (e.g., your-store.myshopify.com)',
      },
      {
        key: 'token',
        label: 'Admin API Access Token',
        placeholder: 'shpat_xxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Found in Settings → Apps → Develop apps → Your App → Admin API access token',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'View payments and manage subscriptions',
    category: 'ecommerce',
    icon: '💳',
    color: '#635bff',
    tokenLabel: 'Secret Key',
    tokenHelpUrl: 'https://dashboard.stripe.com/apikeys',
    placeholder: 'sk_xxxx_xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'View balance and transactions',
      'List customers and subscriptions',
      'View products and prices',
      'List invoices',
    ],
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    description: 'E-commerce email marketing',
    category: 'ecommerce',
    icon: '📧',
    color: '#000000',
    tokenLabel: 'Private API Key',
    tokenHelpUrl: 'https://www.klaviyo.com/account#api-keys-tab',
    placeholder: 'pk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Manage profiles/subscribers',
      'Create and manage lists',
      'View campaigns and flows',
      'Track custom events',
      'View metrics',
    ],
  },
  {
    id: 'printful',
    name: 'Printful',
    description: 'Print-on-demand fulfillment',
    category: 'ecommerce',
    icon: '👕',
    color: '#222222',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://www.printful.com/dashboard/settings/store-settings',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'View store info',
      'List and manage products',
      'Create and track orders',
      'Estimate shipping costs',
      'Browse catalog',
    ],
  },

  // DOCS & DATA
  {
    id: 'notion',
    name: 'Notion',
    description: 'Read and edit Notion pages and databases',
    category: 'docs',
    icon: '📝',
    color: '#000000',
    tokenLabel: 'Integration Token',
    tokenHelpUrl: 'https://www.notion.so/my-integrations',
    placeholder: 'secret_xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Search pages and databases',
      'Read and create pages',
      'Query databases',
      'Append content to pages',
    ],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Query and update Airtable bases',
    category: 'docs',
    icon: '📊',
    color: '#18bfff',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://airtable.com/create/tokens',
    placeholder: 'patxxxxxxxxxxxxxxxx',
    capabilities: [
      'List bases and tables',
      'Query and filter records',
      'Create and update records',
      'Delete records',
    ],
  },
  {
    id: 'docusign',
    name: 'DocuSign',
    description: 'Send and manage electronic signatures',
    category: 'docs',
    icon: '✍️',
    color: '#4C00FF',
    tokenLabel: 'API Credentials',
    tokenHelpUrl: 'https://developers.docusign.com/platform/auth/',
    placeholder: '',
    capabilities: [
      'Send documents for signature',
      'Check envelope status',
      'Download signed documents',
      'List envelopes and recipients',
      'Create signing workflows',
    ],
    fields: [
      {
        key: 'accountId',
        label: 'Account ID',
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        type: 'text',
        helpText: 'Found in DocuSign Admin → API and Keys',
      },
      {
        key: 'integrationKey',
        label: 'Integration Key',
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        type: 'text',
        helpText: 'Create an app in DocuSign Developer Portal',
      },
      {
        key: 'accessToken',
        label: 'Access Token',
        placeholder: 'eyJ0eXAiOiJKV1QiLCJhbGciOi...',
        type: 'password',
        helpText: 'OAuth access token or JWT token',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'hellosign',
    name: 'Dropbox Sign',
    description: 'Electronic signatures via HelloSign',
    category: 'docs',
    icon: '✒️',
    color: '#00b4e6',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://app.hellosign.com/home/myAccount#api',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Send signature requests',
      'Check signature status',
      'Download signed documents',
      'Create templates',
      'List signature requests',
    ],
  },

  // PROJECT MANAGEMENT
  {
    id: 'linear',
    name: 'Linear',
    description: 'Manage issues and projects',
    category: 'project',
    icon: '📐',
    color: '#5e6ad2',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://linear.app/settings/api',
    placeholder: 'lin_api_xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List and manage issues',
      'Create and update issues',
      'View teams and projects',
      'Add comments',
    ],
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Manage Jira issues and boards',
    category: 'project',
    icon: '🎯',
    color: '#0052cc',
    tokenLabel: 'Jira Credentials',
    tokenHelpUrl: 'https://id.atlassian.com/manage-profile/security/api-tokens',
    placeholder: '',
    capabilities: [
      'Search and manage issues',
      'Create and update tickets',
      'View boards and sprints',
      'Add comments and transitions',
    ],
    fields: [
      {
        key: 'site',
        label: 'Jira Site',
        placeholder: 'your-site.atlassian.net',
        type: 'text',
        helpText: 'Your Jira Cloud site domain',
      },
      {
        key: 'email',
        label: 'Email',
        placeholder: 'your-email@example.com',
        type: 'text',
        helpText: 'Your Atlassian account email',
      },
      {
        key: 'token',
        label: 'API Token',
        placeholder: 'ATATT3xFfGF0...',
        type: 'password',
        helpText: 'Create at id.atlassian.com → Security → API tokens',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Manage tasks and projects',
    category: 'project',
    icon: '✅',
    color: '#f06a6a',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://app.asana.com/0/developer-console',
    placeholder: '1/1234567890:abcdefghijklmnop',
    capabilities: [
      'Create and manage tasks',
      'View and update projects',
      'Add comments and attachments',
      'Assign and complete tasks',
      'Search across workspaces',
    ],
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Manage Trello boards and cards',
    category: 'project',
    icon: '📋',
    color: '#0079bf',
    tokenLabel: 'API Credentials',
    tokenHelpUrl: 'https://trello.com/power-ups/admin',
    placeholder: '',
    capabilities: [
      'Create and manage cards',
      'Move cards between lists',
      'Add comments and labels',
      'Manage boards and lists',
      'View members and activity',
    ],
    fields: [
      {
        key: 'apiKey',
        label: 'API Key',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'text',
        helpText: 'Get from trello.com/power-ups/admin → API Key',
      },
      {
        key: 'token',
        label: 'Token',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Click "Token" link next to API Key to generate',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    description: 'Manage ClickUp tasks and spaces',
    category: 'project',
    icon: '🎨',
    color: '#7b68ee',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://app.clickup.com/settings/apps',
    placeholder: 'pk_xxxxxxxxxxxxxxxx',
    capabilities: [
      'Create and manage tasks',
      'View spaces, folders, lists',
      'Update task status and priority',
      'Add comments and time tracking',
      'Manage team workspaces',
    ],
  },
  {
    id: 'monday',
    name: 'Monday.com',
    description: 'Manage Monday boards and items',
    category: 'project',
    icon: '📅',
    color: '#ff3d57',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://monday.com/developers/apps',
    placeholder: 'eyJhbGciOiJIUzI1NiJ9...',
    capabilities: [
      'Create and update items',
      'Manage boards and groups',
      'Update column values',
      'Add updates (comments)',
      'Search and filter items',
    ],
  },
  {
    id: 'jobber',
    name: 'Jobber',
    description: 'Field service management for home services',
    category: 'project',
    icon: '🔧',
    color: '#7ac143',
    tokenLabel: 'OAuth Credentials',
    tokenHelpUrl: 'https://developer.getjobber.com/docs/',
    placeholder: '',
    capabilities: [
      'List and manage clients',
      'Create and view jobs',
      'Manage quotes and invoices',
      'Schedule appointments',
      'Track job status',
    ],
    fields: [
      {
        key: 'clientId',
        label: 'Client ID',
        placeholder: 'your-client-id',
        type: 'text',
        helpText: 'Found in Jobber Developer Center',
      },
      {
        key: 'accessToken',
        label: 'Access Token',
        placeholder: 'your-oauth-access-token',
        type: 'password',
        helpText: 'OAuth access token from authorization flow',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'housecallpro',
    name: 'Housecall Pro',
    description: 'Field service management for contractors',
    category: 'project',
    icon: '🏠',
    color: '#ff6b35',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://docs.housecallpro.com/',
    placeholder: 'hcp_xxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List and manage customers',
      'Create and manage jobs',
      'Schedule appointments',
      'Send estimates and invoices',
      'Track technician status',
    ],
  },
  {
    id: 'toggl',
    name: 'Toggl Track',
    description: 'Time tracking and productivity',
    category: 'project',
    icon: '⏱️',
    color: '#e57cd8',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://track.toggl.com/profile',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Start and stop time entries',
      'List time entries',
      'Manage projects and clients',
      'View reports and summaries',
      'Create and manage workspaces',
    ],
  },
  {
    id: 'workyard',
    name: 'Workyard',
    description: 'Construction workforce management',
    category: 'project',
    icon: '👷',
    color: '#2563eb',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://developers.workyard.com/',
    placeholder: 'wy_xxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Track employee time and GPS',
      'Manage projects and job sites',
      'View labor costs',
      'Schedule crews',
      'Export timesheet data',
    ],
  },

  // ANALYTICS
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    description: 'Query analytics and user behavior',
    category: 'analytics',
    icon: '📈',
    color: '#7856ff',
    tokenLabel: 'API Credentials',
    tokenHelpUrl: 'https://mixpanel.com/settings/project#serviceaccounts',
    placeholder: '',
    capabilities: [
      'Query events and metrics',
      'View funnels and retention',
      'Analyze user behavior',
      'Get segmentation data',
      'Track custom events',
    ],
    fields: [
      {
        key: 'projectToken',
        label: 'Project Token',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'text',
        helpText: 'Found in Project Settings → Project Token',
      },
      {
        key: 'apiSecret',
        label: 'API Secret',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Found in Project Settings → API Secret (or Service Account)',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    description: 'Query product analytics',
    category: 'analytics',
    icon: '📊',
    color: '#1e61e4',
    tokenLabel: 'API Credentials',
    tokenHelpUrl: 'https://analytics.amplitude.com/settings/profile',
    placeholder: '',
    capabilities: [
      'Query events and users',
      'View retention and funnels',
      'Analyze active users',
      'Get revenue metrics',
      'Real-time analytics',
    ],
    fields: [
      {
        key: 'apiKey',
        label: 'API Key',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'text',
        helpText: 'Found in Organization Settings → API Keys',
      },
      {
        key: 'secretKey',
        label: 'Secret Key',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Found in Organization Settings → API Keys',
      },
    ],
    fieldSeparator: '|',
  },

  // AI & VOICE
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'Use GPT, DALL-E, and Whisper',
    category: 'ai',
    icon: '🤖',
    color: '#10a37f',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://platform.openai.com/api-keys',
    placeholder: 'sk-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Chat with GPT models',
      'Generate images with DALL-E',
      'Create embeddings',
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Use Claude models with your own key',
    category: 'ai',
    icon: '🧠',
    color: '#d4a27f',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://console.anthropic.com/settings/keys',
    placeholder: 'sk-ant-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Chat with Claude models',
      'Long context conversations',
      'Code generation',
    ],
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    description: 'Use Grok models',
    category: 'ai',
    icon: '𝕏',
    color: '#000000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://console.x.ai/',
    placeholder: 'xai-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Chat with Grok models',
      'Image generation',
      'Real-time knowledge',
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Ultra-fast AI inference',
    category: 'ai',
    icon: '⚡',
    color: '#f55036',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://console.groq.com/keys',
    placeholder: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Fast Llama and Mixtral inference',
      'Low latency responses',
      'Open source models',
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Use Mistral and Codestral models',
    category: 'ai',
    icon: '🌀',
    color: '#ff7000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://console.mistral.ai/api-keys/',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Chat with Mistral models',
      'Code with Codestral',
      'Create embeddings',
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'AI-powered search and answers',
    category: 'ai',
    icon: '🔍',
    color: '#20808d',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://www.perplexity.ai/settings/api',
    placeholder: 'pplx-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Search-augmented AI',
      'Real-time information',
      'Cited responses',
    ],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    description: 'Run open source AI models',
    category: 'ai',
    icon: '🔄',
    color: '#000000',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://replicate.com/account/api-tokens',
    placeholder: 'r8_xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Run any open source model',
      'Image generation',
      'Audio and video models',
    ],
  },
  {
    id: 'stability',
    name: 'Stability AI',
    description: 'Generate images with Stable Diffusion',
    category: 'ai',
    icon: '🎨',
    color: '#8b5cf6',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://platform.stability.ai/account/keys',
    placeholder: 'sk-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Text-to-image generation',
      'Image upscaling',
      'Multiple SDXL engines',
    ],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Text-to-speech and voice cloning',
    category: 'ai',
    icon: '🎙️',
    color: '#000000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://elevenlabs.io/settings/api-keys',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Text-to-speech',
      'Voice cloning',
      'Multiple voice models',
    ],
  },
  {
    id: 'bfl',
    name: 'Black Forest Labs',
    description: 'Generate images with Flux models',
    category: 'ai',
    icon: '🌲',
    color: '#1a472a',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://api.bfl.ml/',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Flux Pro image generation',
      'Flux Dev and Schnell models',
      'Image-to-image',
      'Inpainting',
    ],
  },
  {
    id: 'runway',
    name: 'Runway',
    description: 'Generate videos with Gen-3 Alpha',
    category: 'ai',
    icon: '🎬',
    color: '#000000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://app.runwayml.com/settings/api-keys',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Text-to-video generation',
      'Image-to-video generation',
      'Gen-3 Alpha Turbo',
    ],
  },
  {
    id: 'luma',
    name: 'Luma AI',
    description: 'Generate videos with Dream Machine',
    category: 'ai',
    icon: '🎥',
    color: '#6366f1',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://lumalabs.ai/dream-machine/api',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Text-to-video generation',
      'Image-to-video generation',
      'Video extension',
    ],
  },
  {
    id: 'suno',
    name: 'Suno',
    description: 'Generate music and songs with AI',
    category: 'ai',
    icon: '🎵',
    color: '#000000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://suno.com/account',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Generate songs from lyrics',
      'Generate from description',
      'Extend existing songs',
    ],
  },
  {
    id: 'canva',
    name: 'Canva',
    description: 'Design platform for graphics and content',
    category: 'ai',
    icon: '🎨',
    color: '#00c4cc',
    tokenLabel: 'Connect API Credentials',
    tokenHelpUrl: 'https://www.canva.dev/docs/connect/quickstart/',
    placeholder: '',
    capabilities: [
      'Create designs from templates',
      'Upload and manage assets',
      'Export designs in various formats',
      'Manage brand kits',
      'Collaborate on designs',
    ],
    fields: [
      {
        key: 'clientId',
        label: 'Client ID',
        placeholder: 'OC-xxxxx-xxxxx',
        type: 'text',
        helpText: 'Found in Canva Developer Portal',
      },
      {
        key: 'clientSecret',
        label: 'Client Secret',
        placeholder: 'cnsec-xxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Found in Canva Developer Portal',
      },
      {
        key: 'accessToken',
        label: 'Access Token',
        placeholder: 'Bearer token from OAuth flow',
        type: 'password',
        helpText: 'OAuth access token',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'descript',
    name: 'Descript',
    description: 'Audio and video editing with AI',
    category: 'ai',
    icon: '🎬',
    color: '#5046e5',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://docs.descriptapi.com/',
    placeholder: 'dscpt_xxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Edit audio and video content',
      'Transcribe media automatically',
      'Generate voice with Overdub',
      'Remove filler words',
      'Export in multiple formats',
    ],
  },

  // COMMUNICATION
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send messages and manage channels',
    category: 'communication',
    icon: '💬',
    color: '#4a154b',
    tokenLabel: 'Bot Token',
    tokenHelpUrl: 'https://api.slack.com/apps',
    placeholder: 'xoxb-xxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Send and read messages',
      'List and manage channels',
      'Search messages',
      'Manage users and reactions',
    ],
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Manage Discord servers and messages',
    category: 'communication',
    icon: '🎮',
    color: '#5865f2',
    tokenLabel: 'Bot Token',
    tokenHelpUrl: 'https://discord.com/developers/applications',
    placeholder: 'MTxxxxxxxxxxxxxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Send and read messages',
      'List servers and channels',
      'Manage roles and members',
      'Add reactions',
    ],
  },
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'Send SMS messages',
    category: 'communication',
    icon: '📱',
    color: '#f22f46',
    tokenLabel: 'Twilio Credentials',
    tokenHelpUrl: 'https://console.twilio.com/',
    placeholder: '',
    capabilities: [
      'Send SMS messages',
      'View message history',
      'List phone numbers',
    ],
    fields: [
      {
        key: 'sid',
        label: 'Account SID',
        placeholder: 'ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'text',
        helpText: 'Found on your Twilio Console dashboard',
      },
      {
        key: 'token',
        label: 'Auth Token',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Found on your Twilio Console dashboard',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'resend',
    name: 'Resend',
    description: 'Modern email API for developers',
    category: 'communication',
    icon: '✉️',
    color: '#000000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://resend.com/api-keys',
    placeholder: 're_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Send emails',
      'View email status',
      'Manage domains',
      'Verify domains',
    ],
  },
  {
    id: 'buffer',
    name: 'Buffer',
    description: 'Social media management',
    category: 'communication',
    icon: '📣',
    color: '#168eea',
    tokenLabel: 'Access Token',
    tokenHelpUrl: 'https://buffer.com/developers/api',
    placeholder: '1/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List connected social profiles',
      'Create and schedule posts',
      'View pending and sent posts',
      'Manage post queue',
      'Share to multiple platforms',
    ],
  },
  {
    id: 'calendly',
    name: 'Calendly',
    description: 'Scheduling and calendar management',
    category: 'communication',
    icon: '📅',
    color: '#006bff',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://calendly.com/integrations/api_webhooks',
    placeholder: 'eyJhbGciOiJIUzI1NiJ9...',
    capabilities: [
      'List event types',
      'View scheduled events',
      'List invitees',
      'Cancel events',
      'Manage webhooks',
    ],
  },
  {
    id: 'telegram',
    name: 'Telegram Bot',
    description: 'Build and manage Telegram bots',
    category: 'communication',
    icon: '✈️',
    color: '#0088cc',
    tokenLabel: 'Bot Token',
    tokenHelpUrl: 'https://core.telegram.org/bots#botfather',
    placeholder: '123456789:ABCdefGHIjklMNOpqrsTUVwxyz',
    capabilities: [
      'Send messages to chats',
      'Send photos and documents',
      'Create inline keyboards',
      'Manage bot commands',
      'Get chat and user info',
    ],
  },
  {
    id: 'skool',
    name: 'Skool',
    description: 'Community and course platform',
    category: 'communication',
    icon: '🎓',
    color: '#facc15',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://www.skool.com/community',
    placeholder: 'sk_xxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Manage community members',
      'Create and manage courses',
      'Post announcements',
      'Track engagement',
      'Manage gamification',
    ],
    comingSoon: true,
  },

  // FINANCE & TRADING
  {
    id: 'coinbase',
    name: 'Coinbase',
    description: 'Manage crypto wallets and check prices',
    category: 'finance',
    icon: '₿',
    color: '#0052ff',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://www.coinbase.com/settings/api',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'View account balances',
      'Get crypto prices',
      'List transactions',
      'Send crypto',
      'Get spot prices',
    ],
  },
  {
    id: 'coinbase-trade',
    name: 'Coinbase Advanced',
    description: 'Full crypto trading with buy/sell capabilities',
    category: 'finance',
    icon: '📈',
    color: '#0052ff',
    tokenLabel: 'Advanced Trade API Credentials',
    tokenHelpUrl: 'https://www.coinbase.com/settings/api',
    placeholder: '',
    capabilities: [
      'Buy and sell crypto',
      'View account balances',
      'List orders and fills',
      'Get market data and prices',
      'Manage portfolio',
    ],
    fields: [
      {
        key: 'apiKey',
        label: 'API Key',
        placeholder: 'organizations/xxx/apiKeys/xxx',
        type: 'text',
        helpText: 'Found in Coinbase → Settings → API → Create API Key (Advanced Trade)',
      },
      {
        key: 'apiSecret',
        label: 'API Secret',
        placeholder: '-----BEGIN EC PRIVATE KEY-----...',
        type: 'password',
        helpText: 'The private key generated when creating the API key',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'alpaca',
    name: 'Alpaca',
    description: 'Commission-free stock trading',
    category: 'finance',
    icon: '🦙',
    color: '#fcd34d',
    tokenLabel: 'API Credentials',
    tokenHelpUrl: 'https://app.alpaca.markets/paper/dashboard/overview',
    placeholder: '',
    capabilities: [
      'Buy and sell stocks',
      'View portfolio and positions',
      'Get stock quotes and bars',
      'Manage orders',
      'View market calendar',
    ],
    fields: [
      {
        key: 'apiKey',
        label: 'API Key ID',
        placeholder: 'PKxxxxxxxxxxxxxxxxxxxx',
        type: 'text',
        helpText: 'Found in Alpaca dashboard → Paper Trading or Live → API Keys',
      },
      {
        key: 'apiSecret',
        label: 'Secret Key',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Generated when creating API key',
      },
      {
        key: 'mode',
        label: 'Trading Mode',
        placeholder: 'paper (or live)',
        type: 'text',
        helpText: 'Enter "paper" for paper trading or "live" for real money',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'alphavantage',
    name: 'Alpha Vantage',
    description: 'Stock market data and technical analysis',
    category: 'finance',
    icon: '📊',
    color: '#4f46e5',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://www.alphavantage.co/support/#api-key',
    placeholder: 'xxxxxxxxxxxxxxxx',
    capabilities: [
      'Get stock quotes and prices',
      'Historical data (daily, weekly, monthly)',
      'Technical indicators (SMA, EMA, RSI, MACD)',
      'Company fundamentals and earnings',
      'Market news and sentiment',
    ],
  },
  {
    id: 'coingecko',
    name: 'CoinGecko',
    description: 'Comprehensive crypto market data',
    category: 'finance',
    icon: '🦎',
    color: '#8dc647',
    tokenLabel: 'API Key (optional for basic)',
    tokenHelpUrl: 'https://www.coingecko.com/en/api',
    placeholder: 'CG-xxxxxxxxxxxxxxxx',
    capabilities: [
      'Get crypto prices and market data',
      'View trending coins',
      'Historical charts and OHLC',
      'Exchange and NFT data',
      'Global market statistics',
    ],
  },
  {
    id: 'newsapi',
    name: 'NewsAPI',
    description: 'Real-time news aggregation',
    category: 'finance',
    icon: '📰',
    color: '#4a5568',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://newsapi.org/register',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Get top headlines',
      'Search news articles',
      'Filter by category and source',
      'Crypto, tech, AI, and business news',
      'Stock and company news',
    ],
  },
  {
    id: 'expensify',
    name: 'Expensify',
    description: 'Expense management and reporting',
    category: 'finance',
    icon: '🧾',
    color: '#1a8917',
    tokenLabel: 'Partner Credentials',
    tokenHelpUrl: 'https://integrations.expensify.com/',
    placeholder: '',
    capabilities: [
      'Create and submit expense reports',
      'Export expense data',
      'Manage policy members',
      'Track receipts',
      'Generate reports (CSV, PDF)',
    ],
    fields: [
      {
        key: 'partnerUserID',
        label: 'Partner User ID',
        placeholder: 'your-partner-user-id',
        type: 'text',
        helpText: 'Found at expensify.com/tools/integrations',
      },
      {
        key: 'partnerUserSecret',
        label: 'Partner User Secret',
        placeholder: 'your-partner-user-secret',
        type: 'password',
        helpText: 'Found at expensify.com/tools/integrations',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'ynab',
    name: 'YNAB',
    description: 'You Need A Budget - personal finance',
    category: 'finance',
    icon: '💰',
    color: '#85c3e9',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://app.ynab.com/settings/developer',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'View budgets and accounts',
      'List transactions',
      'Create transactions',
      'View category balances',
      'Track budget progress',
    ],
  },
  {
    id: 'plaid',
    name: 'Plaid',
    description: 'Connect to bank accounts and financial data',
    category: 'finance',
    icon: '🏦',
    color: '#0977d1',
    tokenLabel: 'API Credentials',
    tokenHelpUrl: 'https://dashboard.plaid.com/developers/keys',
    placeholder: '',
    capabilities: [
      'Link bank accounts',
      'Get account balances',
      'Retrieve transactions',
      'Verify identity',
      'Access investment data',
    ],
    fields: [
      {
        key: 'clientId',
        label: 'Client ID',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'text',
        helpText: 'Found in Plaid Dashboard → Keys',
      },
      {
        key: 'secret',
        label: 'Secret',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Use Sandbox secret for testing, Production for live',
      },
      {
        key: 'env',
        label: 'Environment',
        placeholder: 'sandbox (or production)',
        type: 'text',
        helpText: 'Enter "sandbox" for testing or "production" for live',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'wave',
    name: 'Wave Accounting',
    description: 'Free accounting for small businesses',
    category: 'finance',
    icon: '🌊',
    color: '#1c6dd0',
    tokenLabel: 'OAuth Token',
    tokenHelpUrl: 'https://developer.waveapps.com/hc/en-us',
    placeholder: 'Bearer xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Create and send invoices',
      'Track expenses',
      'View financial reports',
      'Manage customers and vendors',
      'Record payments',
    ],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Connect to 6000+ apps via automation',
    category: 'code',
    icon: '⚡',
    color: '#ff4a00',
    tokenLabel: 'API Key or Webhook URL',
    tokenHelpUrl: 'https://zapier.com/app/settings/integrations',
    placeholder: 'sk-... or https://hooks.zapier.com/...',
    capabilities: [
      'Trigger webhooks',
      'Execute Natural Language Actions (NLA)',
      'Send emails via Zaps',
      'Post to Slack via Zaps',
      'Create tasks in any connected app',
    ],
  },

  // WEBSITES & CMS
  {
    id: 'wordpress',
    name: 'WordPress',
    description: 'Manage WordPress posts and pages',
    category: 'website',
    icon: '🌐',
    color: '#21759b',
    tokenLabel: 'Site Credentials',
    tokenHelpUrl: 'https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/',
    placeholder: '',
    capabilities: [
      'Create and manage posts',
      'Edit pages',
      'Manage categories and tags',
      'List and upload media',
      'View comments',
    ],
    fields: [
      {
        key: 'siteUrl',
        label: 'Site URL',
        placeholder: 'https://yoursite.com',
        type: 'text',
        helpText: 'Your WordPress site URL',
      },
      {
        key: 'username',
        label: 'Username',
        placeholder: 'admin',
        type: 'text',
        helpText: 'Your WordPress username',
      },
      {
        key: 'appPassword',
        label: 'Application Password',
        placeholder: 'xxxx xxxx xxxx xxxx xxxx xxxx',
        type: 'password',
        helpText: 'Generate in Users → Profile → Application Passwords',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'webflow',
    name: 'Webflow',
    description: 'Manage Webflow CMS content',
    category: 'website',
    icon: '🎨',
    color: '#4353ff',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://webflow.com/dashboard/account/integrations',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List sites and collections',
      'Create and edit CMS items',
      'Manage collection content',
      'Publish sites and changes',
      'View domains',
    ],
  },
  {
    id: 'ghost',
    name: 'Ghost',
    description: 'Manage Ghost blog content',
    category: 'website',
    icon: '👻',
    color: '#15171a',
    tokenLabel: 'Admin API Credentials',
    tokenHelpUrl: 'https://ghost.org/docs/admin-api/',
    placeholder: '',
    capabilities: [
      'Create and edit posts',
      'Manage pages',
      'Create and manage tags',
      'List members and users',
      'Get site information',
    ],
    fields: [
      {
        key: 'siteUrl',
        label: 'Ghost Site URL',
        placeholder: 'https://yourblog.com',
        type: 'text',
        helpText: 'Your Ghost blog URL',
      },
      {
        key: 'adminApiKey',
        label: 'Admin API Key',
        placeholder: 'xxxxxxxxxxxxxxxx:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
        type: 'password',
        helpText: 'Found in Settings → Integrations → Add custom integration',
      },
    ],
    fieldSeparator: '|',
  },

  // CRM & SALES
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'CRM, marketing, and sales platform',
    category: 'ecommerce',
    icon: '🧲',
    color: '#ff7a59',
    tokenLabel: 'Private App Access Token',
    tokenHelpUrl: 'https://developers.hubspot.com/docs/api/private-apps',
    placeholder: 'pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    capabilities: [
      'Manage contacts and companies',
      'Create and update deals',
      'Track sales pipeline',
      'Manage marketing campaigns',
      'View analytics and reports',
    ],
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    description: 'Sales CRM and pipeline management',
    category: 'ecommerce',
    icon: '📊',
    color: '#017737',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://pipedrive.readme.io/docs/how-to-find-the-api-token',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Manage deals and contacts',
      'Track sales pipeline',
      'Create and update activities',
      'Manage organizations',
      'View sales reports',
    ],
  },
  {
    id: 'closecrm',
    name: 'Close CRM',
    description: 'Sales CRM for closing deals faster',
    category: 'ecommerce',
    icon: '🎯',
    color: '#2e3a59',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://developer.close.com/',
    placeholder: 'api_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Manage leads and contacts',
      'Track opportunities',
      'Log calls and emails',
      'Create tasks and reminders',
      'View sales reports',
    ],
  },
  {
    id: 'copper',
    name: 'Copper CRM',
    description: 'CRM designed for Google Workspace',
    category: 'ecommerce',
    icon: '🔶',
    color: '#f7941e',
    tokenLabel: 'API Credentials',
    tokenHelpUrl: 'https://developer.copper.com/',
    placeholder: '',
    capabilities: [
      'Manage people and companies',
      'Track opportunities',
      'Log activities and tasks',
      'Sync with Google Workspace',
      'View pipeline reports',
    ],
    fields: [
      {
        key: 'apiKey',
        label: 'API Key',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Found in Settings → Integrations → API Keys',
      },
      {
        key: 'email',
        label: 'User Email',
        placeholder: 'your-email@company.com',
        type: 'text',
        helpText: 'Your Copper account email',
      },
    ],
    fieldSeparator: '|',
  },

  // LOGISTICS & ROUTING
  {
    id: 'route4me',
    name: 'Route4Me',
    description: 'Route optimization and planning',
    category: 'project',
    icon: '🗺️',
    color: '#4caf50',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://route4me.io/dashboard/settings/api',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Optimize delivery routes',
      'Plan multi-stop trips',
      'Track drivers in real-time',
      'Manage addresses and contacts',
      'View route analytics',
    ],
  },
  {
    id: 'onfleet',
    name: 'Onfleet',
    description: 'Last-mile delivery management',
    category: 'project',
    icon: '🚚',
    color: '#ac2bff',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://docs.onfleet.com/reference/authentication',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Create and manage tasks',
      'Assign drivers and teams',
      'Track deliveries in real-time',
      'Optimize routes',
      'View delivery analytics',
    ],
  },

  // SCHEDULING & FORMS
  {
    id: 'acuity',
    name: 'Acuity Scheduling',
    description: 'Online appointment scheduling',
    category: 'communication',
    icon: '📅',
    color: '#1a73e8',
    tokenLabel: 'API Credentials',
    tokenHelpUrl: 'https://acuityscheduling.com/support/article/api-basics/',
    placeholder: '',
    capabilities: [
      'List and manage appointments',
      'View availability',
      'Create and cancel bookings',
      'Manage clients',
      'View calendar schedules',
    ],
    fields: [
      {
        key: 'userId',
        label: 'User ID',
        placeholder: '1234567',
        type: 'text',
        helpText: 'Found in Integrations → API',
      },
      {
        key: 'apiKey',
        label: 'API Key',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Found in Integrations → API',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'typeform',
    name: 'Typeform',
    description: 'Interactive forms and surveys',
    category: 'docs',
    icon: '📋',
    color: '#262627',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://www.typeform.com/developers/get-started/personal-access-token/',
    placeholder: 'tfp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List and manage forms',
      'View form responses',
      'Create new forms',
      'Get form analytics',
      'Manage workspaces',
    ],
  },
  {
    id: 'jotform',
    name: 'Jotform',
    description: 'Online form builder and data collection',
    category: 'docs',
    icon: '📝',
    color: '#f8b500',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://www.jotform.com/developers/api/',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List and manage forms',
      'View form submissions',
      'Create new forms',
      'Get form reports',
      'Manage folders',
    ],
  },

  // LIVE CHAT & MESSAGING
  {
    id: 'crisp',
    name: 'Crisp.chat',
    description: 'Customer messaging platform',
    category: 'communication',
    icon: '💬',
    color: '#1972f5',
    tokenLabel: 'API Credentials',
    tokenHelpUrl: 'https://docs.crisp.chat/guides/rest-api/authentication/',
    placeholder: '',
    capabilities: [
      'List and manage conversations',
      'Send messages to visitors',
      'View visitor profiles',
      'Manage contacts',
      'Track website analytics',
    ],
    fields: [
      {
        key: 'identifier',
        label: 'Token Identifier',
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        type: 'text',
        helpText: 'Found in Settings → Website Settings → Tokens',
      },
      {
        key: 'key',
        label: 'Token Key',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Found in Settings → Website Settings → Tokens',
      },
      {
        key: 'websiteId',
        label: 'Website ID',
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        type: 'text',
        helpText: 'Found in Settings → Website Settings',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'tidio',
    name: 'Tidio',
    description: 'Live chat and chatbot platform',
    category: 'communication',
    icon: '🤖',
    color: '#0066ff',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://www.tidio.com/integrations/',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List conversations',
      'Send messages',
      'View visitor info',
      'Manage contacts',
      'Track chat analytics',
    ],
  },

  // PRODUCTIVITY & TASKS
  {
    id: 'todoist',
    name: 'Todoist',
    description: 'Task management and to-do lists',
    category: 'project',
    icon: '✅',
    color: '#e44332',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://app.todoist.com/app/settings/integrations/developer',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Create and manage tasks',
      'Organize projects',
      'Set due dates and priorities',
      'Add labels and filters',
      'Track productivity',
    ],
  },
  {
    id: 'clockify',
    name: 'Clockify',
    description: 'Free time tracking for teams',
    category: 'project',
    icon: '⏰',
    color: '#03a9f4',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://clockify.me/developers-api',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Start and stop timers',
      'Log time entries',
      'Manage projects and tasks',
      'View time reports',
      'Track team hours',
    ],
  },
  {
    id: 'harvest',
    name: 'Harvest',
    description: 'Time tracking and invoicing',
    category: 'project',
    icon: '🌾',
    color: '#fa5d00',
    tokenLabel: 'API Credentials',
    tokenHelpUrl: 'https://id.getharvest.com/developers',
    placeholder: '',
    capabilities: [
      'Track time on projects',
      'Create and send invoices',
      'Manage expenses',
      'View reports and analytics',
      'Manage clients and projects',
    ],
    fields: [
      {
        key: 'accountId',
        label: 'Account ID',
        placeholder: '1234567',
        type: 'text',
        helpText: 'Found in Settings → Developers → Personal Access Tokens',
      },
      {
        key: 'accessToken',
        label: 'Access Token',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Create a Personal Access Token in Developers settings',
      },
    ],
    fieldSeparator: '|',
  },

  // ONLINE LEARNING
  {
    id: 'teachable',
    name: 'Teachable',
    description: 'Online course creation platform',
    category: 'communication',
    icon: '📚',
    color: '#00bfa5',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://docs.teachable.com/docs/getting-started',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List and manage courses',
      'View enrolled students',
      'Track course progress',
      'Manage sales and coupons',
      'View revenue reports',
    ],
  },
];

// Get connectors by category
export function getConnectorsByCategory(category: ConnectorConfig['category']): ConnectorConfig[] {
  return CONNECTORS.filter(c => c.category === category);
}

// Get a specific connector by ID
export function getConnectorById(id: string): ConnectorConfig | undefined {
  return CONNECTORS.find(c => c.id === id);
}

// Get all active (non-coming-soon) connectors
export function getActiveConnectors(): ConnectorConfig[] {
  return CONNECTORS.filter(c => !c.comingSoon);
}

// Category labels for UI
export const CATEGORY_LABELS: Record<ConnectorConfig['category'], string> = {
  code: 'Code & Development',
  ecommerce: 'E-Commerce',
  docs: 'Docs & Data',
  project: 'Project Management',
  analytics: 'Analytics',
  ai: 'AI & Voice',
  communication: 'Communication',
  website: 'Websites & CMS',
  finance: 'Finance & Trading',
};
