/**
 * CONNECTORS CONFIGURATION
 * Defines all available external service integrations
 */

export interface ConnectorField {
  key: string;
  label: string;
  placeholder: string;
  type?: 'text' | 'password';
  helpText?: string;
}

export interface ConnectorConfig {
  id: string;
  name: string;
  description: string;
  category: 'code' | 'ecommerce' | 'docs' | 'project' | 'analytics' | 'ai' | 'communication' | 'website';
  icon: string; // We'll use simple text icons or could be URLs
  color: string; // Brand color for UI
  tokenLabel: string; // e.g., "Personal Access Token" or "API Key"
  tokenHelpUrl: string; // Link to docs on how to get the token
  placeholder: string; // Placeholder text for input
  capabilities: string[]; // What the AI can do with this connector
  comingSoon?: boolean; // If true, show as "Coming Soon"
  fields?: ConnectorField[]; // For connectors that need multiple inputs (e.g., Supabase)
  fieldSeparator?: string; // How to join multiple fields when storing (default: '|')
}

export const CONNECTORS: ConnectorConfig[] = [
  // CODE & DEV
  {
    id: 'github',
    name: 'GitHub',
    description: 'Read, write, and manage code repositories',
    category: 'code',
    icon: '🐙',
    color: '#24292e',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://github.com/settings/tokens',
    placeholder: 'ghp_xxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Read repository files',
      'Create and edit files',
      'Create commits and branches',
      'Open pull requests',
      'Manage issues',
    ],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'Manage GitLab repositories and CI/CD',
    category: 'code',
    icon: '🦊',
    color: '#fc6d26',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://gitlab.com/-/profile/personal_access_tokens',
    placeholder: 'glpat-xxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Read repository files',
      'List and manage projects',
      'View merge requests and issues',
      'Monitor CI/CD pipelines',
    ],
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Manage deployments and projects',
    category: 'code',
    icon: '▲',
    color: '#000000',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://vercel.com/account/tokens',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List projects',
      'View deployments',
      'Check deployment status',
      'View environment variables',
      'Trigger redeployments',
    ],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Manage database and authentication',
    category: 'code',
    icon: '⚡',
    color: '#3ecf8e',
    tokenLabel: 'Project Credentials',
    tokenHelpUrl: 'https://supabase.com/dashboard/project/_/settings/api',
    placeholder: '', // Not used when fields is defined
    capabilities: [
      'List and query database tables',
      'Insert, update, delete records',
      'View table schemas',
      'List authenticated users',
      'Run custom queries',
    ],
    fields: [
      {
        key: 'url',
        label: 'Project URL',
        placeholder: 'https://abcd1234.supabase.co',
        type: 'text',
        helpText: 'Find this in Settings → API → Project URL',
      },
      {
        key: 'key',
        label: 'Service Role Key',
        placeholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        type: 'password',
        helpText: 'Find this in Settings → API → service_role (secret)',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'Manage DNS, Workers, and CDN',
    category: 'code',
    icon: '☁️',
    color: '#f38020',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List and manage DNS zones',
      'Create, update, delete DNS records',
      'Purge cache',
      'List and manage Workers',
      'View analytics',
    ],
  },
  {
    id: 'upstash',
    name: 'Upstash',
    description: 'Serverless Redis database',
    category: 'code',
    icon: '🔺',
    color: '#00e9a3',
    tokenLabel: 'Redis Credentials',
    tokenHelpUrl: 'https://console.upstash.com/',
    placeholder: '',
    capabilities: [
      'Get, set, delete keys',
      'Hash operations',
      'List operations',
      'Key management',
      'Database info',
    ],
    fields: [
      {
        key: 'url',
        label: 'REST URL',
        placeholder: 'https://xxxxxx.upstash.io',
        type: 'text',
        helpText: 'Found in your Upstash Redis database details',
      },
      {
        key: 'token',
        label: 'REST Token',
        placeholder: 'AxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxQ=',
        type: 'password',
        helpText: 'Found in your Upstash Redis database details',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'n8n',
    name: 'n8n',
    description: 'Workflow automation platform',
    category: 'code',
    icon: '🔗',
    color: '#ea4b71',
    tokenLabel: 'n8n Credentials',
    tokenHelpUrl: 'https://docs.n8n.io/api/',
    placeholder: '',
    capabilities: [
      'List and manage workflows',
      'Execute workflows',
      'View executions',
      'Trigger webhooks',
      'Activate/deactivate workflows',
    ],
    fields: [
      {
        key: 'url',
        label: 'n8n Host URL',
        placeholder: 'https://your-n8n.example.com',
        type: 'text',
        helpText: 'Your n8n instance URL (self-hosted or cloud)',
      },
      {
        key: 'token',
        label: 'API Key',
        placeholder: 'n8n_api_xxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Create in n8n Settings → API',
      },
    ],
    fieldSeparator: '|',
  },

  // E-COMMERCE
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Manage your Shopify store',
    category: 'ecommerce',
    icon: '🛒',
    color: '#96bf48',
    tokenLabel: 'Store Credentials',
    tokenHelpUrl: 'https://admin.shopify.com/store/YOUR_STORE/settings/apps/development',
    placeholder: '',
    capabilities: [
      'View and edit products',
      'Manage inventory',
      'View orders and customers',
      'Update prices',
      'List collections',
    ],
    fields: [
      {
        key: 'store',
        label: 'Store Domain',
        placeholder: 'your-store.myshopify.com',
        type: 'text',
        helpText: 'Your Shopify store domain (e.g., your-store.myshopify.com)',
      },
      {
        key: 'token',
        label: 'Admin API Access Token',
        placeholder: 'shpat_xxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Found in Settings → Apps → Develop apps → Your App → Admin API access token',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'View payments and manage subscriptions',
    category: 'ecommerce',
    icon: '💳',
    color: '#635bff',
    tokenLabel: 'Secret Key',
    tokenHelpUrl: 'https://dashboard.stripe.com/apikeys',
    placeholder: 'sk_xxxx_xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'View balance and transactions',
      'List customers and subscriptions',
      'View products and prices',
      'List invoices',
    ],
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    description: 'Manage crypto wallets and trading',
    category: 'ecommerce',
    icon: '₿',
    color: '#0052ff',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://www.coinbase.com/settings/api',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'View account balances',
      'Get crypto prices',
      'List transactions',
      'Send crypto',
      'Get spot prices',
    ],
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    description: 'E-commerce email marketing',
    category: 'ecommerce',
    icon: '📧',
    color: '#000000',
    tokenLabel: 'Private API Key',
    tokenHelpUrl: 'https://www.klaviyo.com/account#api-keys-tab',
    placeholder: 'pk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Manage profiles/subscribers',
      'Create and manage lists',
      'View campaigns and flows',
      'Track custom events',
      'View metrics',
    ],
  },
  {
    id: 'printful',
    name: 'Printful',
    description: 'Print-on-demand fulfillment',
    category: 'ecommerce',
    icon: '👕',
    color: '#222222',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://www.printful.com/dashboard/settings/store-settings',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'View store info',
      'List and manage products',
      'Create and track orders',
      'Estimate shipping costs',
      'Browse catalog',
    ],
  },

  // DOCS & DATA
  {
    id: 'notion',
    name: 'Notion',
    description: 'Read and edit Notion pages and databases',
    category: 'docs',
    icon: '📝',
    color: '#000000',
    tokenLabel: 'Integration Token',
    tokenHelpUrl: 'https://www.notion.so/my-integrations',
    placeholder: 'secret_xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Search pages and databases',
      'Read and create pages',
      'Query databases',
      'Append content to pages',
    ],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Query and update Airtable bases',
    category: 'docs',
    icon: '📊',
    color: '#18bfff',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://airtable.com/create/tokens',
    placeholder: 'patxxxxxxxxxxxxxxxx',
    capabilities: [
      'List bases and tables',
      'Query and filter records',
      'Create and update records',
      'Delete records',
    ],
  },

  // PROJECT MANAGEMENT
  {
    id: 'linear',
    name: 'Linear',
    description: 'Manage issues and projects',
    category: 'project',
    icon: '📐',
    color: '#5e6ad2',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://linear.app/settings/api',
    placeholder: 'lin_api_xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List and manage issues',
      'Create and update issues',
      'View teams and projects',
      'Add comments',
    ],
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Manage Jira issues and boards',
    category: 'project',
    icon: '🎯',
    color: '#0052cc',
    tokenLabel: 'Jira Credentials',
    tokenHelpUrl: 'https://id.atlassian.com/manage-profile/security/api-tokens',
    placeholder: '',
    capabilities: [
      'Search and manage issues',
      'Create and update tickets',
      'View boards and sprints',
      'Add comments and transitions',
    ],
    fields: [
      {
        key: 'site',
        label: 'Jira Site',
        placeholder: 'your-site.atlassian.net',
        type: 'text',
        helpText: 'Your Jira Cloud site domain',
      },
      {
        key: 'email',
        label: 'Email',
        placeholder: 'your-email@example.com',
        type: 'text',
        helpText: 'Your Atlassian account email',
      },
      {
        key: 'token',
        label: 'API Token',
        placeholder: 'ATATT3xFfGF0...',
        type: 'password',
        helpText: 'Create at id.atlassian.com → Security → API tokens',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Manage tasks and projects',
    category: 'project',
    icon: '✅',
    color: '#f06a6a',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://app.asana.com/0/developer-console',
    placeholder: '1/1234567890:abcdefghijklmnop',
    capabilities: [
      'Create tasks',
      'Update task status',
      'View projects',
      'Assign tasks',
    ],
    comingSoon: true,
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Manage Trello boards and cards',
    category: 'project',
    icon: '📋',
    color: '#0079bf',
    tokenLabel: 'API Key + Token',
    tokenHelpUrl: 'https://trello.com/power-ups/admin',
    placeholder: 'key:token format',
    capabilities: [
      'Create cards',
      'Move cards between lists',
      'Add comments',
      'Manage boards',
    ],
    comingSoon: true,
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    description: 'Manage ClickUp tasks and spaces',
    category: 'project',
    icon: '🎨',
    color: '#7b68ee',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://app.clickup.com/settings/apps',
    placeholder: 'pk_xxxxxxxxxxxxxxxx',
    capabilities: [
      'Create tasks',
      'Update status',
      'View spaces',
      'Manage lists',
    ],
    comingSoon: true,
  },
  {
    id: 'monday',
    name: 'Monday.com',
    description: 'Manage Monday boards and items',
    category: 'project',
    icon: '📅',
    color: '#ff3d57',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://monday.com/developers/apps',
    placeholder: 'eyJhbGciOiJIUzI1NiJ9...',
    capabilities: [
      'Create items',
      'Update columns',
      'View boards',
      'Manage groups',
    ],
    comingSoon: true,
  },

  // ANALYTICS
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    description: 'Query analytics data',
    category: 'analytics',
    icon: '📈',
    color: '#7856ff',
    tokenLabel: 'Service Account Secret',
    tokenHelpUrl: 'https://mixpanel.com/settings/project#serviceaccounts',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Query events',
      'View funnels',
      'Analyze user behavior',
    ],
    comingSoon: true,
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    description: 'Query product analytics',
    category: 'analytics',
    icon: '📊',
    color: '#1e61e4',
    tokenLabel: 'API Key + Secret',
    tokenHelpUrl: 'https://analytics.amplitude.com/settings/profile',
    placeholder: 'api_key:secret_key',
    capabilities: [
      'Query events',
      'View charts',
      'Analyze cohorts',
    ],
    comingSoon: true,
  },

  // AI & VOICE
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'Use GPT, DALL-E, and Whisper',
    category: 'ai',
    icon: '🤖',
    color: '#10a37f',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://platform.openai.com/api-keys',
    placeholder: 'sk-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Chat with GPT models',
      'Generate images with DALL-E',
      'Create embeddings',
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Use Claude models with your own key',
    category: 'ai',
    icon: '🧠',
    color: '#d4a27f',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://console.anthropic.com/settings/keys',
    placeholder: 'sk-ant-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Chat with Claude models',
      'Long context conversations',
      'Code generation',
    ],
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    description: 'Use Grok models',
    category: 'ai',
    icon: '𝕏',
    color: '#000000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://console.x.ai/',
    placeholder: 'xai-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Chat with Grok models',
      'Image generation',
      'Real-time knowledge',
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Ultra-fast AI inference',
    category: 'ai',
    icon: '⚡',
    color: '#f55036',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://console.groq.com/keys',
    placeholder: 'gsk_xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Fast Llama and Mixtral inference',
      'Low latency responses',
      'Open source models',
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Use Mistral and Codestral models',
    category: 'ai',
    icon: '🌀',
    color: '#ff7000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://console.mistral.ai/api-keys/',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Chat with Mistral models',
      'Code with Codestral',
      'Create embeddings',
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'AI-powered search and answers',
    category: 'ai',
    icon: '🔍',
    color: '#20808d',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://www.perplexity.ai/settings/api',
    placeholder: 'pplx-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Search-augmented AI',
      'Real-time information',
      'Cited responses',
    ],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    description: 'Run open source AI models',
    category: 'ai',
    icon: '🔄',
    color: '#000000',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://replicate.com/account/api-tokens',
    placeholder: 'r8_xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Run any open source model',
      'Image generation',
      'Audio and video models',
    ],
  },
  {
    id: 'stability',
    name: 'Stability AI',
    description: 'Generate images with Stable Diffusion',
    category: 'ai',
    icon: '🎨',
    color: '#8b5cf6',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://platform.stability.ai/account/keys',
    placeholder: 'sk-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Text-to-image generation',
      'Image upscaling',
      'Multiple SDXL engines',
    ],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Text-to-speech and voice cloning',
    category: 'ai',
    icon: '🎙️',
    color: '#000000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://elevenlabs.io/settings/api-keys',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Text-to-speech',
      'Voice cloning',
      'Multiple voice models',
    ],
  },
  {
    id: 'bfl',
    name: 'Black Forest Labs',
    description: 'Generate images with Flux models',
    category: 'ai',
    icon: '🌲',
    color: '#1a472a',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://api.bfl.ml/',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Flux Pro image generation',
      'Flux Dev and Schnell models',
      'Image-to-image',
      'Inpainting',
    ],
  },
  {
    id: 'runway',
    name: 'Runway',
    description: 'Generate videos with Gen-3 Alpha',
    category: 'ai',
    icon: '🎬',
    color: '#000000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://app.runwayml.com/settings/api-keys',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Text-to-video generation',
      'Image-to-video generation',
      'Gen-3 Alpha Turbo',
    ],
  },
  {
    id: 'luma',
    name: 'Luma AI',
    description: 'Generate videos with Dream Machine',
    category: 'ai',
    icon: '🎥',
    color: '#6366f1',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://lumalabs.ai/dream-machine/api',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Text-to-video generation',
      'Image-to-video generation',
      'Video extension',
    ],
  },
  {
    id: 'suno',
    name: 'Suno',
    description: 'Generate music and songs with AI',
    category: 'ai',
    icon: '🎵',
    color: '#000000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://suno.com/account',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Generate songs from lyrics',
      'Generate from description',
      'Extend existing songs',
    ],
  },

  // COMMUNICATION
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send messages and manage channels',
    category: 'communication',
    icon: '💬',
    color: '#4a154b',
    tokenLabel: 'Bot Token',
    tokenHelpUrl: 'https://api.slack.com/apps',
    placeholder: 'xoxb-xxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Send and read messages',
      'List and manage channels',
      'Search messages',
      'Manage users and reactions',
    ],
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Manage Discord servers and messages',
    category: 'communication',
    icon: '🎮',
    color: '#5865f2',
    tokenLabel: 'Bot Token',
    tokenHelpUrl: 'https://discord.com/developers/applications',
    placeholder: 'MTxxxxxxxxxxxxxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Send and read messages',
      'List servers and channels',
      'Manage roles and members',
      'Add reactions',
    ],
  },
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'Send SMS messages',
    category: 'communication',
    icon: '📱',
    color: '#f22f46',
    tokenLabel: 'Twilio Credentials',
    tokenHelpUrl: 'https://console.twilio.com/',
    placeholder: '',
    capabilities: [
      'Send SMS messages',
      'View message history',
      'List phone numbers',
    ],
    fields: [
      {
        key: 'sid',
        label: 'Account SID',
        placeholder: 'ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'text',
        helpText: 'Found on your Twilio Console dashboard',
      },
      {
        key: 'token',
        label: 'Auth Token',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        type: 'password',
        helpText: 'Found on your Twilio Console dashboard',
      },
    ],
    fieldSeparator: '|',
  },
  {
    id: 'resend',
    name: 'Resend',
    description: 'Modern email API for developers',
    category: 'communication',
    icon: '✉️',
    color: '#000000',
    tokenLabel: 'API Key',
    tokenHelpUrl: 'https://resend.com/api-keys',
    placeholder: 're_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Send emails',
      'View email status',
      'Manage domains',
      'Verify domains',
    ],
  },
  {
    id: 'buffer',
    name: 'Buffer',
    description: 'Social media management',
    category: 'communication',
    icon: '📣',
    color: '#168eea',
    tokenLabel: 'Access Token',
    tokenHelpUrl: 'https://buffer.com/developers/api',
    placeholder: '1/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'List connected social profiles',
      'Create and schedule posts',
      'View pending and sent posts',
      'Manage post queue',
      'Share to multiple platforms',
    ],
  },
  {
    id: 'calendly',
    name: 'Calendly',
    description: 'Scheduling and calendar management',
    category: 'communication',
    icon: '📅',
    color: '#006bff',
    tokenLabel: 'Personal Access Token',
    tokenHelpUrl: 'https://calendly.com/integrations/api_webhooks',
    placeholder: 'eyJhbGciOiJIUzI1NiJ9...',
    capabilities: [
      'List event types',
      'View scheduled events',
      'List invitees',
      'Cancel events',
      'Manage webhooks',
    ],
  },

  // WEBSITES & CMS
  {
    id: 'wordpress',
    name: 'WordPress',
    description: 'Manage WordPress posts and pages',
    category: 'website',
    icon: '🌐',
    color: '#21759b',
    tokenLabel: 'Application Password',
    tokenHelpUrl: 'https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/',
    placeholder: 'username:xxxx xxxx xxxx xxxx',
    capabilities: [
      'Create posts',
      'Edit pages',
      'Manage media',
      'Update content',
    ],
    comingSoon: true,
  },
  {
    id: 'webflow',
    name: 'Webflow',
    description: 'Manage Webflow CMS content',
    category: 'website',
    icon: '🎨',
    color: '#4353ff',
    tokenLabel: 'API Token',
    tokenHelpUrl: 'https://webflow.com/dashboard/account/integrations',
    placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    capabilities: [
      'Edit CMS items',
      'Manage collections',
      'Publish changes',
    ],
    comingSoon: true,
  },
  {
    id: 'ghost',
    name: 'Ghost',
    description: 'Manage Ghost blog content',
    category: 'website',
    icon: '👻',
    color: '#15171a',
    tokenLabel: 'Admin API Key',
    tokenHelpUrl: 'https://ghost.org/docs/admin-api/',
    placeholder: 'xxxxxxxxxxxxxxxxxxxx:yyyyyyyyyyyyyyyy',
    capabilities: [
      'Create posts',
      'Edit content',
      'Manage tags',
    ],
    comingSoon: true,
  },
];

// Get connectors by category
export function getConnectorsByCategory(category: ConnectorConfig['category']): ConnectorConfig[] {
  return CONNECTORS.filter(c => c.category === category);
}

// Get a specific connector by ID
export function getConnectorById(id: string): ConnectorConfig | undefined {
  return CONNECTORS.find(c => c.id === id);
}

// Get all active (non-coming-soon) connectors
export function getActiveConnectors(): ConnectorConfig[] {
  return CONNECTORS.filter(c => !c.comingSoon);
}

// Category labels for UI
export const CATEGORY_LABELS: Record<ConnectorConfig['category'], string> = {
  code: 'Code & Development',
  ecommerce: 'E-Commerce',
  docs: 'Docs & Data',
  project: 'Project Management',
  analytics: 'Analytics',
  ai: 'AI & Voice',
  communication: 'Communication',
  website: 'Websites & CMS',
};
