/**
 * ANTHROPIC FILES API - Download Endpoint
 *
 * PURPOSE:
 * - Download files generated by Anthropic Skills (xlsx, pptx, docx, pdf)
 * - Proxy between client and Anthropic's Files API
 * - Requires authentication
 *
 * USAGE:
 * GET /api/files/anthropic/{fileId}
 */

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from '@/lib/supabase/server-auth';
import { downloadAnthropicFile } from '@/lib/anthropic/client';

export const dynamic = 'force-dynamic';

export async function GET(
  _request: NextRequest,
  { params }: { params: { fileId: string } }
) {
  try {
    // Authenticate user
    const session = await getServerSession();

    if (!session?.user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const user = session.user;

    const { fileId } = params;

    if (!fileId) {
      return NextResponse.json(
        { error: 'File ID is required' },
        { status: 400 }
      );
    }

    console.log(`[Anthropic Files API] Downloading file: ${fileId} for user: ${user.id}`);

    // Download file from Anthropic
    const { data, filename, mimeType } = await downloadAnthropicFile(fileId);

    // Return file with appropriate headers
    return new NextResponse(data, {
      status: 200,
      headers: {
        'Content-Type': mimeType,
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': data.byteLength.toString(),
        'Cache-Control': 'private, max-age=3600',
      },
    });
  } catch (error) {
    console.error('[Anthropic Files API] Download error:', error);

    // Check for specific error types
    if (error instanceof Error) {
      if (error.message.includes('not found') || error.message.includes('404')) {
        return NextResponse.json(
          { error: 'File not found or expired' },
          { status: 404 }
        );
      }
      if (error.message.includes('rate limit')) {
        return NextResponse.json(
          { error: 'Rate limit exceeded. Please try again later.' },
          { status: 429 }
        );
      }
    }

    return NextResponse.json(
      { error: 'Failed to download file' },
      { status: 500 }
    );
  }
}
