/**
 * ANTHROPIC FILES API - Download Endpoint
 *
 * PURPOSE:
 * - Download files generated by Anthropic Skills (xlsx, pptx, docx, pdf)
 * - Proxy between client and Anthropic's Files API
 * - Requires authentication
 *
 * USAGE:
 * GET /api/files/anthropic/{fileId}
 */

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from '@/lib/supabase/server-auth';
import { downloadAnthropicFile } from '@/lib/anthropic/client';
import { logger } from '@/lib/logger';

const log = logger('AnthropicFilesAPI');

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

export async function GET(_request: NextRequest, { params }: { params: { fileId: string } }) {
  try {
    // Authenticate user
    const session = await getServerSession();

    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // User is authenticated (session.user verified above)

    const { fileId } = params;

    if (!fileId) {
      return NextResponse.json({ error: 'File ID is required' }, { status: 400 });
    }

    // Processing authenticated file download request

    // Download file from Anthropic
    const result = await downloadAnthropicFile(fileId);

    // Return file with appropriate headers
    return new NextResponse(result.data, {
      status: 200,
      headers: {
        'Content-Type': result.mimeType,
        'Content-Disposition': `attachment; filename="${result.filename}"`,
        'Content-Length': result.data.byteLength.toString(),
        'Cache-Control': 'private, max-age=3600',
      },
    });
  } catch (error) {
    log.error('[Anthropic Files API] Download error:', error instanceof Error ? error : { error });

    // Check for specific error types
    if (error instanceof Error) {
      if (error.message.includes('not found') || error.message.includes('404')) {
        return NextResponse.json({ error: 'File not found or expired' }, { status: 404 });
      }
      if (error.message.includes('rate limit')) {
        return NextResponse.json(
          { error: 'Rate limit exceeded. Please try again later.' },
          { status: 429 }
        );
      }
    }

    return NextResponse.json({ error: 'Failed to download file' }, { status: 500 });
  }
}
