/**
 * COMPOSIO TOOLKITS CONFIGURATION
 * ================================
 *
 * 150+ app integrations available through Composio.
 * Organized by category for easy browsing and discovery.
 */

import type { ToolkitConfig, ToolkitCategory } from './types';

// ============================================================================
// POPULAR TOOLKITS (shown prominently in UI)
// ============================================================================

export const POPULAR_TOOLKITS: ToolkitConfig[] = [
  // Communication - Essential
  {
    id: 'GMAIL',
    displayName: 'Gmail',
    description: 'Send emails, manage inbox, search messages',
    icon: '📧',
    category: 'communication',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'SLACK',
    displayName: 'Slack',
    description: 'Send messages, manage channels, automate workflows',
    icon: '💬',
    category: 'communication',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'DISCORD',
    displayName: 'Discord',
    description: 'Manage servers, send messages, moderate communities',
    icon: '🎮',
    category: 'communication',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'MICROSOFT_TEAMS',
    displayName: 'Microsoft Teams',
    description: 'Chat, meet, collaborate with your team',
    icon: '👥',
    category: 'communication',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'WHATSAPP',
    displayName: 'WhatsApp Business',
    description: 'Send messages, manage customer conversations',
    icon: '📱',
    category: 'communication',
    authType: 'api_key',
    popular: true,
  },

  // Productivity - Must Have
  {
    id: 'NOTION',
    displayName: 'Notion',
    description: 'Create pages, manage databases, organize workspace',
    icon: '📝',
    category: 'productivity',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'GOOGLE_DOCS',
    displayName: 'Google Docs',
    description: 'Create and edit documents collaboratively',
    icon: '📄',
    category: 'productivity',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'GOOGLE_SHEETS',
    displayName: 'Google Sheets',
    description: 'Create spreadsheets, analyze data, automate reports',
    icon: '📊',
    category: 'productivity',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'AIRTABLE',
    displayName: 'Airtable',
    description: 'Build databases, track projects, organize anything',
    icon: '📋',
    category: 'productivity',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'TODOIST',
    displayName: 'Todoist',
    description: 'Manage tasks, set reminders, boost productivity',
    icon: '✅',
    category: 'productivity',
    authType: 'oauth2',
    popular: true,
  },

  // Social Media - High Demand
  {
    id: 'TWITTER',
    displayName: 'Twitter/X',
    description: 'Post tweets, manage timeline, engage followers',
    icon: '🐦',
    category: 'social',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'LINKEDIN',
    displayName: 'LinkedIn',
    description: 'Post updates, manage connections, recruit talent',
    icon: '💼',
    category: 'social',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'INSTAGRAM',
    displayName: 'Instagram',
    description: 'Post content, manage stories, engage audience',
    icon: '📸',
    category: 'social',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'YOUTUBE',
    displayName: 'YouTube',
    description: 'Upload videos, manage channel, analyze performance',
    icon: '🎬',
    category: 'social',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'TIKTOK',
    displayName: 'TikTok',
    description: 'Post videos, track analytics, engage followers',
    icon: '🎵',
    category: 'social',
    authType: 'oauth2',
    popular: true,
  },

  // Development - Core
  {
    id: 'GITHUB',
    displayName: 'GitHub',
    description: 'Manage repos, create issues, automate workflows',
    icon: '🐙',
    category: 'development',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'JIRA',
    displayName: 'Jira',
    description: 'Track issues, manage sprints, plan projects',
    icon: '📌',
    category: 'development',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'LINEAR',
    displayName: 'Linear',
    description: 'Modern issue tracking for software teams',
    icon: '⚡',
    category: 'development',
    authType: 'oauth2',
    popular: true,
  },
];

// ============================================================================
// ALL AVAILABLE TOOLKITS (150+ integrations)
// ============================================================================

export const ALL_TOOLKITS: ToolkitConfig[] = [
  // ==================== COMMUNICATION ====================
  {
    id: 'GMAIL',
    displayName: 'Gmail',
    description: 'Send emails, manage inbox, search messages',
    icon: '📧',
    category: 'communication',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'SLACK',
    displayName: 'Slack',
    description: 'Send messages, manage channels, automate workflows',
    icon: '💬',
    category: 'communication',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'DISCORD',
    displayName: 'Discord',
    description: 'Manage servers, send messages, moderate communities',
    icon: '🎮',
    category: 'communication',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'MICROSOFT_TEAMS',
    displayName: 'Microsoft Teams',
    description: 'Chat, meet, collaborate with your team',
    icon: '👥',
    category: 'communication',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'WHATSAPP',
    displayName: 'WhatsApp Business',
    description: 'Send messages, manage customer conversations',
    icon: '📱',
    category: 'communication',
    authType: 'api_key',
    popular: true,
  },
  {
    id: 'TELEGRAM',
    displayName: 'Telegram',
    description: 'Send messages, manage bots, automate notifications',
    icon: '✈️',
    category: 'communication',
    authType: 'api_key',
  },
  {
    id: 'ZOOM',
    displayName: 'Zoom',
    description: 'Schedule meetings, manage recordings, send invites',
    icon: '📹',
    category: 'communication',
    authType: 'oauth2',
  },
  {
    id: 'TWILIO',
    displayName: 'Twilio',
    description: 'Send SMS, make calls, manage communications',
    icon: '📞',
    category: 'communication',
    authType: 'api_key',
  },
  {
    id: 'SENDGRID',
    displayName: 'SendGrid',
    description: 'Send transactional emails at scale',
    icon: '📨',
    category: 'communication',
    authType: 'api_key',
  },
  {
    id: 'MAILCHIMP',
    displayName: 'Mailchimp',
    description: 'Create campaigns, manage subscribers, track opens',
    icon: '🐵',
    category: 'communication',
    authType: 'oauth2',
  },
  {
    id: 'INTERCOM',
    displayName: 'Intercom',
    description: 'Customer messaging platform for support',
    icon: '💭',
    category: 'communication',
    authType: 'oauth2',
  },
  {
    id: 'MICROSOFT_OUTLOOK',
    displayName: 'Outlook',
    description: 'Manage emails, calendars, and contacts',
    icon: '📬',
    category: 'communication',
    authType: 'oauth2',
  },
  {
    id: 'POSTMARK',
    displayName: 'Postmark',
    description: 'Reliable transactional email delivery',
    icon: '📮',
    category: 'communication',
    authType: 'api_key',
  },
  {
    id: 'LOOM',
    displayName: 'Loom',
    description: 'Record and share video messages',
    icon: '🎥',
    category: 'communication',
    authType: 'oauth2',
  },

  // ==================== PRODUCTIVITY ====================
  {
    id: 'NOTION',
    displayName: 'Notion',
    description: 'Create pages, manage databases, organize workspace',
    icon: '📝',
    category: 'productivity',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'GOOGLE_DOCS',
    displayName: 'Google Docs',
    description: 'Create and edit documents collaboratively',
    icon: '📄',
    category: 'productivity',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'GOOGLE_SHEETS',
    displayName: 'Google Sheets',
    description: 'Create spreadsheets, analyze data, automate reports',
    icon: '📊',
    category: 'productivity',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'AIRTABLE',
    displayName: 'Airtable',
    description: 'Build databases, track projects, organize anything',
    icon: '📋',
    category: 'productivity',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'TODOIST',
    displayName: 'Todoist',
    description: 'Manage tasks, set reminders, boost productivity',
    icon: '✅',
    category: 'productivity',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'ASANA',
    displayName: 'Asana',
    description: 'Project management and team collaboration',
    icon: '🎯',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'TRELLO',
    displayName: 'Trello',
    description: 'Kanban boards for visual project management',
    icon: '📌',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'MONDAY',
    displayName: 'Monday.com',
    description: 'Work OS for teams to manage projects',
    icon: '📅',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'CLICKUP',
    displayName: 'ClickUp',
    description: 'All-in-one productivity platform',
    icon: '🚀',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'BASECAMP',
    displayName: 'Basecamp',
    description: 'Project management and team communication',
    icon: '🏕️',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'CODA',
    displayName: 'Coda',
    description: 'Doc that brings words, data, and teams together',
    icon: '📓',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'EVERNOTE',
    displayName: 'Evernote',
    description: 'Note-taking and organization tool',
    icon: '🐘',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'CONFLUENCE',
    displayName: 'Confluence',
    description: 'Team workspace for documentation',
    icon: '📚',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'GOOGLE_SLIDES',
    displayName: 'Google Slides',
    description: 'Create presentations online',
    icon: '📽️',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'MIRO',
    displayName: 'Miro',
    description: 'Online whiteboard for team collaboration',
    icon: '🎨',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'FIGMA',
    displayName: 'Figma',
    description: 'Collaborative design and prototyping',
    icon: '🎭',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'SMARTSHEET',
    displayName: 'Smartsheet',
    description: 'Enterprise work management platform',
    icon: '📑',
    category: 'productivity',
    authType: 'oauth2',
  },
  {
    id: 'WRIKE',
    displayName: 'Wrike',
    description: 'Versatile project management software',
    icon: '📐',
    category: 'productivity',
    authType: 'oauth2',
  },

  // ==================== SOCIAL MEDIA ====================
  {
    id: 'TWITTER',
    displayName: 'Twitter/X',
    description: 'Post tweets, manage timeline, engage followers',
    icon: '🐦',
    category: 'social',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'LINKEDIN',
    displayName: 'LinkedIn',
    description: 'Post updates, manage connections, recruit talent',
    icon: '💼',
    category: 'social',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'INSTAGRAM',
    displayName: 'Instagram',
    description: 'Post content, manage stories, engage audience',
    icon: '📸',
    category: 'social',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'YOUTUBE',
    displayName: 'YouTube',
    description: 'Upload videos, manage channel, analyze performance',
    icon: '🎬',
    category: 'social',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'TIKTOK',
    displayName: 'TikTok',
    description: 'Post videos, track analytics, engage followers',
    icon: '🎵',
    category: 'social',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'FACEBOOK',
    displayName: 'Facebook',
    description: 'Manage pages, post content, run ads',
    icon: '👍',
    category: 'social',
    authType: 'oauth2',
  },
  {
    id: 'PINTEREST',
    displayName: 'Pinterest',
    description: 'Pin images, manage boards, drive traffic',
    icon: '📍',
    category: 'social',
    authType: 'oauth2',
  },
  {
    id: 'REDDIT',
    displayName: 'Reddit',
    description: 'Post content, engage communities, monitor mentions',
    icon: '🤖',
    category: 'social',
    authType: 'oauth2',
  },
  {
    id: 'THREADS',
    displayName: 'Threads',
    description: "Post text updates on Meta's new platform",
    icon: '🧵',
    category: 'social',
    authType: 'oauth2',
  },
  {
    id: 'MASTODON',
    displayName: 'Mastodon',
    description: 'Decentralized social networking',
    icon: '🐘',
    category: 'social',
    authType: 'oauth2',
  },
  {
    id: 'BLUESKY',
    displayName: 'Bluesky',
    description: 'Open social network protocol',
    icon: '🦋',
    category: 'social',
    authType: 'oauth2',
  },
  {
    id: 'BUFFER',
    displayName: 'Buffer',
    description: 'Social media scheduling and analytics',
    icon: '🔄',
    category: 'social',
    authType: 'oauth2',
  },
  {
    id: 'HOOTSUITE',
    displayName: 'Hootsuite',
    description: 'Social media management platform',
    icon: '🦉',
    category: 'social',
    authType: 'oauth2',
  },
  {
    id: 'SPROUT_SOCIAL',
    displayName: 'Sprout Social',
    description: 'Social media management and analytics',
    icon: '🌱',
    category: 'social',
    authType: 'oauth2',
  },

  // ==================== DEVELOPMENT ====================
  {
    id: 'GITHUB',
    displayName: 'GitHub',
    description: 'Manage repos, create issues, automate workflows',
    icon: '🐙',
    category: 'development',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'JIRA',
    displayName: 'Jira',
    description: 'Track issues, manage sprints, plan projects',
    icon: '📌',
    category: 'development',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'LINEAR',
    displayName: 'Linear',
    description: 'Modern issue tracking for software teams',
    icon: '⚡',
    category: 'development',
    authType: 'oauth2',
    popular: true,
  },
  {
    id: 'GITLAB',
    displayName: 'GitLab',
    description: 'Complete DevOps platform in a single app',
    icon: '🦊',
    category: 'development',
    authType: 'oauth2',
  },
  {
    id: 'BITBUCKET',
    displayName: 'Bitbucket',
    description: 'Git repository management for teams',
    icon: '🪣',
    category: 'development',
    authType: 'oauth2',
  },
  {
    id: 'SENTRY',
    displayName: 'Sentry',
    description: 'Error tracking and performance monitoring',
    icon: '🐛',
    category: 'development',
    authType: 'api_key',
  },
  {
    id: 'DATADOG',
    displayName: 'Datadog',
    description: 'Monitoring and security platform',
    icon: '🐕',
    category: 'development',
    authType: 'api_key',
  },
  {
    id: 'PAGERDUTY',
    displayName: 'PagerDuty',
    description: 'Incident management and response',
    icon: '🚨',
    category: 'development',
    authType: 'oauth2',
  },
  {
    id: 'VERCEL',
    displayName: 'Vercel',
    description: 'Deploy and host web applications',
    icon: '▲',
    category: 'development',
    authType: 'oauth2',
  },
  {
    id: 'NETLIFY',
    displayName: 'Netlify',
    description: 'Web development and deployment platform',
    icon: '🌐',
    category: 'development',
    authType: 'oauth2',
  },
  {
    id: 'HEROKU',
    displayName: 'Heroku',
    description: 'Cloud application platform',
    icon: '☁️',
    category: 'development',
    authType: 'oauth2',
  },
  {
    id: 'AWS',
    displayName: 'AWS',
    description: 'Amazon Web Services cloud platform',
    icon: '🔶',
    category: 'development',
    authType: 'api_key',
  },
  {
    id: 'AZURE',
    displayName: 'Azure',
    description: 'Microsoft cloud computing platform',
    icon: '🔷',
    category: 'development',
    authType: 'oauth2',
  },
  {
    id: 'GCP',
    displayName: 'Google Cloud',
    description: 'Google Cloud Platform services',
    icon: '☁️',
    category: 'development',
    authType: 'oauth2',
  },
  {
    id: 'DIGITALOCEAN',
    displayName: 'DigitalOcean',
    description: 'Cloud infrastructure provider',
    icon: '🌊',
    category: 'development',
    authType: 'api_key',
  },
  {
    id: 'SUPABASE',
    displayName: 'Supabase',
    description: 'Open source Firebase alternative',
    icon: '⚡',
    category: 'development',
    authType: 'api_key',
  },
  {
    id: 'FIREBASE',
    displayName: 'Firebase',
    description: "Google's app development platform",
    icon: '🔥',
    category: 'development',
    authType: 'api_key',
  },
  {
    id: 'MONGODB',
    displayName: 'MongoDB Atlas',
    description: 'Cloud database service',
    icon: '🍃',
    category: 'development',
    authType: 'api_key',
  },
  {
    id: 'PLANETSCALE',
    displayName: 'PlanetScale',
    description: 'Serverless MySQL platform',
    icon: '🪐',
    category: 'development',
    authType: 'api_key',
  },
  {
    id: 'DOCKER',
    displayName: 'Docker Hub',
    description: 'Container image registry',
    icon: '🐳',
    category: 'development',
    authType: 'oauth2',
  },

  // ==================== CRM ====================
  {
    id: 'HUBSPOT',
    displayName: 'HubSpot',
    description: 'CRM, marketing, sales, and service software',
    icon: '🧲',
    category: 'crm',
    authType: 'oauth2',
  },
  {
    id: 'SALESFORCE',
    displayName: 'Salesforce',
    description: 'Enterprise CRM platform',
    icon: '☁️',
    category: 'crm',
    authType: 'oauth2',
  },
  {
    id: 'PIPEDRIVE',
    displayName: 'Pipedrive',
    description: 'Sales CRM and pipeline management',
    icon: '💰',
    category: 'crm',
    authType: 'oauth2',
  },
  {
    id: 'ZOHO_CRM',
    displayName: 'Zoho CRM',
    description: 'Customer relationship management',
    icon: '📇',
    category: 'crm',
    authType: 'oauth2',
  },
  {
    id: 'FRESHSALES',
    displayName: 'Freshsales',
    description: 'AI-powered CRM for sales teams',
    icon: '🧊',
    category: 'crm',
    authType: 'api_key',
  },
  {
    id: 'CLOSE',
    displayName: 'Close',
    description: 'CRM built for inside sales teams',
    icon: '📞',
    category: 'crm',
    authType: 'api_key',
  },
  {
    id: 'COPPER',
    displayName: 'Copper',
    description: 'CRM for Google Workspace',
    icon: '🥉',
    category: 'crm',
    authType: 'oauth2',
  },
  {
    id: 'INSIGHTLY',
    displayName: 'Insightly',
    description: 'CRM and project management',
    icon: '💡',
    category: 'crm',
    authType: 'api_key',
  },
  {
    id: 'ACTIVECAMPAIGN',
    displayName: 'ActiveCampaign',
    description: 'Marketing automation and CRM',
    icon: '⚡',
    category: 'crm',
    authType: 'api_key',
  },

  // ==================== FINANCE ====================
  {
    id: 'STRIPE',
    displayName: 'Stripe',
    description: 'Payment processing and billing',
    icon: '💳',
    category: 'finance',
    authType: 'api_key',
  },
  {
    id: 'QUICKBOOKS',
    displayName: 'QuickBooks',
    description: 'Accounting and invoicing software',
    icon: '📒',
    category: 'finance',
    authType: 'oauth2',
  },
  {
    id: 'XERO',
    displayName: 'Xero',
    description: 'Online accounting software',
    icon: '📘',
    category: 'finance',
    authType: 'oauth2',
  },
  {
    id: 'PAYPAL',
    displayName: 'PayPal',
    description: 'Online payments and transfers',
    icon: '💵',
    category: 'finance',
    authType: 'oauth2',
  },
  {
    id: 'SQUARE',
    displayName: 'Square',
    description: 'Payment and business tools',
    icon: '⬛',
    category: 'finance',
    authType: 'oauth2',
  },
  {
    id: 'PLAID',
    displayName: 'Plaid',
    description: 'Financial data connectivity',
    icon: '🔗',
    category: 'finance',
    authType: 'api_key',
  },
  {
    id: 'BREX',
    displayName: 'Brex',
    description: 'Corporate cards and expense management',
    icon: '💎',
    category: 'finance',
    authType: 'oauth2',
  },
  {
    id: 'WISE',
    displayName: 'Wise',
    description: 'International money transfers',
    icon: '🌍',
    category: 'finance',
    authType: 'api_key',
  },
  {
    id: 'MERCURY',
    displayName: 'Mercury',
    description: 'Banking for startups',
    icon: '🏦',
    category: 'finance',
    authType: 'oauth2',
  },
  {
    id: 'FRESHBOOKS',
    displayName: 'FreshBooks',
    description: 'Invoicing and accounting',
    icon: '📗',
    category: 'finance',
    authType: 'oauth2',
  },
  {
    id: 'WAVE',
    displayName: 'Wave',
    description: 'Free accounting software',
    icon: '🌊',
    category: 'finance',
    authType: 'oauth2',
  },

  // ==================== CALENDAR ====================
  {
    id: 'GOOGLE_CALENDAR',
    displayName: 'Google Calendar',
    description: 'Schedule events, set reminders, share calendars',
    icon: '📅',
    category: 'calendar',
    authType: 'oauth2',
  },
  {
    id: 'CALENDLY',
    displayName: 'Calendly',
    description: 'Scheduling automation platform',
    icon: '🗓️',
    category: 'calendar',
    authType: 'oauth2',
  },
  {
    id: 'CAL',
    displayName: 'Cal.com',
    description: 'Open source scheduling infrastructure',
    icon: '📆',
    category: 'calendar',
    authType: 'oauth2',
  },
  {
    id: 'MICROSOFT_CALENDAR',
    displayName: 'Outlook Calendar',
    description: 'Microsoft calendar management',
    icon: '📅',
    category: 'calendar',
    authType: 'oauth2',
  },
  {
    id: 'ACUITY',
    displayName: 'Acuity Scheduling',
    description: 'Online appointment scheduling',
    icon: '⏰',
    category: 'calendar',
    authType: 'oauth2',
  },
  {
    id: 'DOODLE',
    displayName: 'Doodle',
    description: 'Meeting scheduling tool',
    icon: '🎯',
    category: 'calendar',
    authType: 'oauth2',
  },
  {
    id: 'SAVVYCAL',
    displayName: 'SavvyCal',
    description: 'Personalized scheduling links',
    icon: '✨',
    category: 'calendar',
    authType: 'oauth2',
  },

  // ==================== STORAGE ====================
  {
    id: 'GOOGLE_DRIVE',
    displayName: 'Google Drive',
    description: 'Cloud storage and file sharing',
    icon: '💾',
    category: 'storage',
    authType: 'oauth2',
  },
  {
    id: 'DROPBOX',
    displayName: 'Dropbox',
    description: 'File hosting and synchronization',
    icon: '📦',
    category: 'storage',
    authType: 'oauth2',
  },
  {
    id: 'ONEDRIVE',
    displayName: 'OneDrive',
    description: 'Microsoft cloud storage',
    icon: '☁️',
    category: 'storage',
    authType: 'oauth2',
  },
  {
    id: 'BOX',
    displayName: 'Box',
    description: 'Enterprise content management',
    icon: '📁',
    category: 'storage',
    authType: 'oauth2',
  },
  {
    id: 'AWS_S3',
    displayName: 'AWS S3',
    description: 'Object storage service',
    icon: '🪣',
    category: 'storage',
    authType: 'api_key',
  },
  {
    id: 'CLOUDFLARE_R2',
    displayName: 'Cloudflare R2',
    description: 'Zero egress fee object storage',
    icon: '🔶',
    category: 'storage',
    authType: 'api_key',
  },
  {
    id: 'UPLOADTHING',
    displayName: 'UploadThing',
    description: 'File uploads for developers',
    icon: '📤',
    category: 'storage',
    authType: 'api_key',
  },

  // ==================== ANALYTICS ====================
  {
    id: 'GOOGLE_ANALYTICS',
    displayName: 'Google Analytics',
    description: 'Web analytics and insights',
    icon: '📈',
    category: 'analytics',
    authType: 'oauth2',
  },
  {
    id: 'MIXPANEL',
    displayName: 'Mixpanel',
    description: 'Product analytics platform',
    icon: '📊',
    category: 'analytics',
    authType: 'api_key',
  },
  {
    id: 'AMPLITUDE',
    displayName: 'Amplitude',
    description: 'Product intelligence platform',
    icon: '📉',
    category: 'analytics',
    authType: 'api_key',
  },
  {
    id: 'POSTHOG',
    displayName: 'PostHog',
    description: 'Open source product analytics',
    icon: '🦔',
    category: 'analytics',
    authType: 'api_key',
  },
  {
    id: 'HOTJAR',
    displayName: 'Hotjar',
    description: 'Heatmaps and behavior analytics',
    icon: '🔥',
    category: 'analytics',
    authType: 'api_key',
  },
  {
    id: 'SEGMENT',
    displayName: 'Segment',
    description: 'Customer data platform',
    icon: '🔀',
    category: 'analytics',
    authType: 'api_key',
  },
  {
    id: 'HEAP',
    displayName: 'Heap',
    description: 'Digital insights platform',
    icon: '📐',
    category: 'analytics',
    authType: 'api_key',
  },
  {
    id: 'PLAUSIBLE',
    displayName: 'Plausible',
    description: 'Privacy-friendly analytics',
    icon: '🍃',
    category: 'analytics',
    authType: 'api_key',
  },

  // ==================== MARKETING ====================
  {
    id: 'GOOGLE_ADS',
    displayName: 'Google Ads',
    description: 'Online advertising platform',
    icon: '📢',
    category: 'marketing',
    authType: 'oauth2',
  },
  {
    id: 'FACEBOOK_ADS',
    displayName: 'Facebook Ads',
    description: 'Social media advertising',
    icon: '📣',
    category: 'marketing',
    authType: 'oauth2',
  },
  {
    id: 'LINKEDIN_ADS',
    displayName: 'LinkedIn Ads',
    description: 'B2B advertising platform',
    icon: '🎯',
    category: 'marketing',
    authType: 'oauth2',
  },
  {
    id: 'KLAVIYO',
    displayName: 'Klaviyo',
    description: 'Email and SMS marketing',
    icon: '💌',
    category: 'marketing',
    authType: 'api_key',
  },
  {
    id: 'CONVERTKIT',
    displayName: 'ConvertKit',
    description: 'Email marketing for creators',
    icon: '✉️',
    category: 'marketing',
    authType: 'api_key',
  },
  {
    id: 'DRIP',
    displayName: 'Drip',
    description: 'Ecommerce marketing automation',
    icon: '💧',
    category: 'marketing',
    authType: 'api_key',
  },
  {
    id: 'CUSTOMER_IO',
    displayName: 'Customer.io',
    description: 'Marketing automation platform',
    icon: '👤',
    category: 'marketing',
    authType: 'api_key',
  },
  {
    id: 'BEEHIIV',
    displayName: 'Beehiiv',
    description: 'Newsletter platform for creators',
    icon: '🐝',
    category: 'marketing',
    authType: 'api_key',
  },
  {
    id: 'SUBSTACK',
    displayName: 'Substack',
    description: 'Newsletter publishing platform',
    icon: '📰',
    category: 'marketing',
    authType: 'oauth2',
  },

  // ==================== ECOMMERCE ====================
  {
    id: 'SHOPIFY',
    displayName: 'Shopify',
    description: 'Ecommerce platform for online stores',
    icon: '🛒',
    category: 'ecommerce',
    authType: 'oauth2',
  },
  {
    id: 'WOOCOMMERCE',
    displayName: 'WooCommerce',
    description: 'WordPress ecommerce plugin',
    icon: '🛍️',
    category: 'ecommerce',
    authType: 'api_key',
  },
  {
    id: 'BIGCOMMERCE',
    displayName: 'BigCommerce',
    description: 'Enterprise ecommerce platform',
    icon: '🏪',
    category: 'ecommerce',
    authType: 'oauth2',
  },
  {
    id: 'SQUARESPACE',
    displayName: 'Squarespace',
    description: 'Website builder and ecommerce',
    icon: '⬜',
    category: 'ecommerce',
    authType: 'oauth2',
  },
  {
    id: 'GUMROAD',
    displayName: 'Gumroad',
    description: 'Sell digital products directly',
    icon: '💸',
    category: 'ecommerce',
    authType: 'oauth2',
  },
  {
    id: 'LEMONSQUEEZY',
    displayName: 'Lemon Squeezy',
    description: 'Payments for SaaS and digital products',
    icon: '🍋',
    category: 'ecommerce',
    authType: 'api_key',
  },
  {
    id: 'PADDLE',
    displayName: 'Paddle',
    description: 'Revenue delivery for SaaS',
    icon: '🏓',
    category: 'ecommerce',
    authType: 'api_key',
  },

  // ==================== HR ====================
  {
    id: 'GREENHOUSE',
    displayName: 'Greenhouse',
    description: 'Applicant tracking system',
    icon: '🌿',
    category: 'hr',
    authType: 'oauth2',
  },
  {
    id: 'LEVER',
    displayName: 'Lever',
    description: 'Talent acquisition suite',
    icon: '⚙️',
    category: 'hr',
    authType: 'oauth2',
  },
  {
    id: 'WORKDAY',
    displayName: 'Workday',
    description: 'Enterprise HR management',
    icon: '👔',
    category: 'hr',
    authType: 'oauth2',
  },
  {
    id: 'BAMBOOHR',
    displayName: 'BambooHR',
    description: 'HR software for small business',
    icon: '🎍',
    category: 'hr',
    authType: 'api_key',
  },
  {
    id: 'GUSTO',
    displayName: 'Gusto',
    description: 'Payroll and HR platform',
    icon: '💼',
    category: 'hr',
    authType: 'oauth2',
  },
  {
    id: 'RIPPLING',
    displayName: 'Rippling',
    description: 'HR, IT, and Finance platform',
    icon: '🌊',
    category: 'hr',
    authType: 'oauth2',
  },
  {
    id: 'DEEL',
    displayName: 'Deel',
    description: 'Global payroll and compliance',
    icon: '🌍',
    category: 'hr',
    authType: 'oauth2',
  },

  // ==================== SUPPORT ====================
  {
    id: 'ZENDESK',
    displayName: 'Zendesk',
    description: 'Customer service and support',
    icon: '🎧',
    category: 'support',
    authType: 'oauth2',
  },
  {
    id: 'FRESHDESK',
    displayName: 'Freshdesk',
    description: 'Customer support software',
    icon: '🎫',
    category: 'support',
    authType: 'api_key',
  },
  {
    id: 'CRISP',
    displayName: 'Crisp',
    description: 'Customer messaging platform',
    icon: '💬',
    category: 'support',
    authType: 'api_key',
  },
  {
    id: 'HELPSCOUT',
    displayName: 'Help Scout',
    description: 'Help desk for growing teams',
    icon: '🦮',
    category: 'support',
    authType: 'oauth2',
  },
  {
    id: 'DRIFT',
    displayName: 'Drift',
    description: 'Conversational marketing platform',
    icon: '🗣️',
    category: 'support',
    authType: 'oauth2',
  },
  {
    id: 'FRONT',
    displayName: 'Front',
    description: 'Customer communication hub',
    icon: '📬',
    category: 'support',
    authType: 'oauth2',
  },

  // ==================== AUTOMATION ====================
  {
    id: 'ZAPIER',
    displayName: 'Zapier',
    description: 'Workflow automation platform',
    icon: '⚡',
    category: 'automation',
    authType: 'api_key',
  },
  {
    id: 'MAKE',
    displayName: 'Make',
    description: 'Visual automation platform',
    icon: '🔧',
    category: 'automation',
    authType: 'api_key',
  },
  {
    id: 'N8N',
    displayName: 'n8n',
    description: 'Open source workflow automation',
    icon: '🔄',
    category: 'automation',
    authType: 'api_key',
  },
  {
    id: 'PIPEDREAM',
    displayName: 'Pipedream',
    description: 'Serverless integration platform',
    icon: '🚰',
    category: 'automation',
    authType: 'api_key',
  },
  {
    id: 'IFTTT',
    displayName: 'IFTTT',
    description: 'Simple automation for consumers',
    icon: '🔀',
    category: 'automation',
    authType: 'oauth2',
  },
  {
    id: 'ACTIVEPIECES',
    displayName: 'Activepieces',
    description: 'Open source automation tool',
    icon: '🧩',
    category: 'automation',
    authType: 'api_key',
  },

  // ==================== MEDIA ====================
  {
    id: 'SPOTIFY',
    displayName: 'Spotify',
    description: 'Music streaming and playlists',
    icon: '🎵',
    category: 'media',
    authType: 'oauth2',
  },
  {
    id: 'APPLE_MUSIC',
    displayName: 'Apple Music',
    description: "Apple's music streaming service",
    icon: '🍎',
    category: 'media',
    authType: 'oauth2',
  },
  {
    id: 'SOUNDCLOUD',
    displayName: 'SoundCloud',
    description: 'Audio streaming platform',
    icon: '☁️',
    category: 'media',
    authType: 'oauth2',
  },
  {
    id: 'VIMEO',
    displayName: 'Vimeo',
    description: 'Professional video hosting',
    icon: '🎥',
    category: 'media',
    authType: 'oauth2',
  },
  {
    id: 'TWITCH',
    displayName: 'Twitch',
    description: 'Live streaming platform',
    icon: '📺',
    category: 'media',
    authType: 'oauth2',
  },
  {
    id: 'UNSPLASH',
    displayName: 'Unsplash',
    description: 'Free high-resolution photos',
    icon: '📷',
    category: 'media',
    authType: 'api_key',
  },
  {
    id: 'PEXELS',
    displayName: 'Pexels',
    description: 'Free stock photos and videos',
    icon: '🖼️',
    category: 'media',
    authType: 'api_key',
  },
  {
    id: 'CLOUDINARY',
    displayName: 'Cloudinary',
    description: 'Image and video management',
    icon: '☁️',
    category: 'media',
    authType: 'api_key',
  },

  // ==================== EDUCATION ====================
  {
    id: 'CANVAS',
    displayName: 'Canvas LMS',
    description: 'Learning management system',
    icon: '🎓',
    category: 'education',
    authType: 'oauth2',
  },
  {
    id: 'TEACHABLE',
    displayName: 'Teachable',
    description: 'Online course platform',
    icon: '📚',
    category: 'education',
    authType: 'oauth2',
  },
  {
    id: 'THINKIFIC',
    displayName: 'Thinkific',
    description: 'Create and sell online courses',
    icon: '🧠',
    category: 'education',
    authType: 'oauth2',
  },
  {
    id: 'PODIA',
    displayName: 'Podia',
    description: 'Digital products and memberships',
    icon: '🏠',
    category: 'education',
    authType: 'oauth2',
  },

  // ==================== TRAVEL ====================
  {
    id: 'GOOGLE_MAPS',
    displayName: 'Google Maps',
    description: 'Maps, directions, and places',
    icon: '🗺️',
    category: 'travel',
    authType: 'api_key',
  },
  {
    id: 'UBER',
    displayName: 'Uber',
    description: 'Ride-hailing and delivery',
    icon: '🚗',
    category: 'travel',
    authType: 'oauth2',
  },
  {
    id: 'LYFT',
    displayName: 'Lyft',
    description: 'Rideshare platform',
    icon: '🚕',
    category: 'travel',
    authType: 'oauth2',
  },
  {
    id: 'AIRBNB',
    displayName: 'Airbnb',
    description: 'Vacation rentals and experiences',
    icon: '🏠',
    category: 'travel',
    authType: 'oauth2',
  },
  {
    id: 'EXPEDIA',
    displayName: 'Expedia',
    description: 'Travel booking platform',
    icon: '✈️',
    category: 'travel',
    authType: 'oauth2',
  },
  {
    id: 'DOORDASH',
    displayName: 'DoorDash',
    description: 'Food delivery service',
    icon: '🍔',
    category: 'travel',
    authType: 'oauth2',
  },
  {
    id: 'INSTACART',
    displayName: 'Instacart',
    description: 'Grocery delivery',
    icon: '🥕',
    category: 'travel',
    authType: 'oauth2',
  },
];

// ============================================================================
// TOOLKIT HELPERS
// ============================================================================

/**
 * Group toolkits by category for organized display
 */
export const TOOLKITS_BY_CATEGORY: Record<ToolkitCategory, ToolkitConfig[]> = {
  communication: ALL_TOOLKITS.filter((t) => t.category === 'communication'),
  productivity: ALL_TOOLKITS.filter((t) => t.category === 'productivity'),
  social: ALL_TOOLKITS.filter((t) => t.category === 'social'),
  development: ALL_TOOLKITS.filter((t) => t.category === 'development'),
  crm: ALL_TOOLKITS.filter((t) => t.category === 'crm'),
  finance: ALL_TOOLKITS.filter((t) => t.category === 'finance'),
  calendar: ALL_TOOLKITS.filter((t) => t.category === 'calendar'),
  storage: ALL_TOOLKITS.filter((t) => t.category === 'storage'),
  analytics: ALL_TOOLKITS.filter((t) => t.category === 'analytics'),
  marketing: ALL_TOOLKITS.filter((t) => t.category === 'marketing'),
  ecommerce: ALL_TOOLKITS.filter((t) => t.category === 'ecommerce'),
  hr: ALL_TOOLKITS.filter((t) => t.category === 'hr'),
  support: ALL_TOOLKITS.filter((t) => t.category === 'support'),
  automation: ALL_TOOLKITS.filter((t) => t.category === 'automation'),
  media: ALL_TOOLKITS.filter((t) => t.category === 'media'),
  education: ALL_TOOLKITS.filter((t) => t.category === 'education'),
  travel: ALL_TOOLKITS.filter((t) => t.category === 'travel'),
};

/**
 * Get toolkit config by ID
 */
export function getToolkitById(id: string): ToolkitConfig | undefined {
  return ALL_TOOLKITS.find((t) => t.id === id || t.id === id.toUpperCase());
}

/**
 * Get toolkits by category
 */
export function getToolkitsByCategory(category: ToolkitCategory): ToolkitConfig[] {
  return TOOLKITS_BY_CATEGORY[category] || [];
}

/**
 * Get popular toolkits
 */
export function getPopularToolkits(): ToolkitConfig[] {
  return POPULAR_TOOLKITS;
}

/**
 * Search toolkits by name or description
 */
export function searchToolkits(query: string): ToolkitConfig[] {
  const lowerQuery = query.toLowerCase();
  return ALL_TOOLKITS.filter(
    (t) =>
      t.displayName.toLowerCase().includes(lowerQuery) ||
      t.description.toLowerCase().includes(lowerQuery) ||
      t.id.toLowerCase().includes(lowerQuery)
  );
}

/**
 * Get total count of available integrations
 */
export function getTotalIntegrationsCount(): number {
  return ALL_TOOLKITS.length;
}
